/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * AutoOrderEmail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-13T15:46:39.276-04:00[America/Indianapolis]")
public class AutoOrderEmail {
  public static final String SERIALIZED_NAME_BOUNCE_DIAGNOSTIC_CODE = "bounce_diagnostic_code";
  @SerializedName(SERIALIZED_NAME_BOUNCE_DIAGNOSTIC_CODE)
  private String bounceDiagnosticCode;

  public static final String SERIALIZED_NAME_BOUNCE_DTS = "bounce_dts";
  @SerializedName(SERIALIZED_NAME_BOUNCE_DTS)
  private String bounceDts;

  public static final String SERIALIZED_NAME_BOUNCE_SUB_TYPE = "bounce_sub_type";
  @SerializedName(SERIALIZED_NAME_BOUNCE_SUB_TYPE)
  private String bounceSubType;

  public static final String SERIALIZED_NAME_BOUNCE_TYPE = "bounce_type";
  @SerializedName(SERIALIZED_NAME_BOUNCE_TYPE)
  private String bounceType;

  public static final String SERIALIZED_NAME_CLICKED = "clicked";
  @SerializedName(SERIALIZED_NAME_CLICKED)
  private Boolean clicked;

  public static final String SERIALIZED_NAME_CLICKED_DTS = "clicked_dts";
  @SerializedName(SERIALIZED_NAME_CLICKED_DTS)
  private String clickedDts;

  public static final String SERIALIZED_NAME_DELIVERED = "delivered";
  @SerializedName(SERIALIZED_NAME_DELIVERED)
  private Boolean delivered;

  public static final String SERIALIZED_NAME_DELIVERY_DTS = "delivery_dts";
  @SerializedName(SERIALIZED_NAME_DELIVERY_DTS)
  private String deliveryDts;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_INTERNAL = "internal";
  @SerializedName(SERIALIZED_NAME_INTERNAL)
  private Boolean internal;

  public static final String SERIALIZED_NAME_MESSAGE_ID = "message_id";
  @SerializedName(SERIALIZED_NAME_MESSAGE_ID)
  private String messageId;

  public static final String SERIALIZED_NAME_OPENED = "opened";
  @SerializedName(SERIALIZED_NAME_OPENED)
  private Boolean opened;

  public static final String SERIALIZED_NAME_OPENED_DTS = "opened_dts";
  @SerializedName(SERIALIZED_NAME_OPENED_DTS)
  private String openedDts;

  public static final String SERIALIZED_NAME_REPORTING_MTA = "reporting_mta";
  @SerializedName(SERIALIZED_NAME_REPORTING_MTA)
  private String reportingMta;

  public static final String SERIALIZED_NAME_SEND_DTS = "send_dts";
  @SerializedName(SERIALIZED_NAME_SEND_DTS)
  private String sendDts;

  public static final String SERIALIZED_NAME_SKIP_REASON = "skip_reason";
  @SerializedName(SERIALIZED_NAME_SKIP_REASON)
  private String skipReason;

  public static final String SERIALIZED_NAME_SKIPPED = "skipped";
  @SerializedName(SERIALIZED_NAME_SKIPPED)
  private Boolean skipped;

  public static final String SERIALIZED_NAME_SMTP_RESPONSE = "smtp_response";
  @SerializedName(SERIALIZED_NAME_SMTP_RESPONSE)
  private String smtpResponse;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private String subject;

  public AutoOrderEmail() { 
  }

  public AutoOrderEmail bounceDiagnosticCode(String bounceDiagnosticCode) {
    
    this.bounceDiagnosticCode = bounceDiagnosticCode;
    return this;
  }

   /**
   * Get bounceDiagnosticCode
   * @return bounceDiagnosticCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBounceDiagnosticCode() {
    return bounceDiagnosticCode;
  }


  public void setBounceDiagnosticCode(String bounceDiagnosticCode) {
    this.bounceDiagnosticCode = bounceDiagnosticCode;
  }


  public AutoOrderEmail bounceDts(String bounceDts) {
    
    this.bounceDts = bounceDts;
    return this;
  }

   /**
   * Date/time that the email was bounced
   * @return bounceDts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date/time that the email was bounced")

  public String getBounceDts() {
    return bounceDts;
  }


  public void setBounceDts(String bounceDts) {
    this.bounceDts = bounceDts;
  }


  public AutoOrderEmail bounceSubType(String bounceSubType) {
    
    this.bounceSubType = bounceSubType;
    return this;
  }

   /**
   * Get bounceSubType
   * @return bounceSubType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBounceSubType() {
    return bounceSubType;
  }


  public void setBounceSubType(String bounceSubType) {
    this.bounceSubType = bounceSubType;
  }


  public AutoOrderEmail bounceType(String bounceType) {
    
    this.bounceType = bounceType;
    return this;
  }

   /**
   * Get bounceType
   * @return bounceType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBounceType() {
    return bounceType;
  }


  public void setBounceType(String bounceType) {
    this.bounceType = bounceType;
  }


  public AutoOrderEmail clicked(Boolean clicked) {
    
    this.clicked = clicked;
    return this;
  }

   /**
   * Get clicked
   * @return clicked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getClicked() {
    return clicked;
  }


  public void setClicked(Boolean clicked) {
    this.clicked = clicked;
  }


  public AutoOrderEmail clickedDts(String clickedDts) {
    
    this.clickedDts = clickedDts;
    return this;
  }

   /**
   * Date/time that the email was clicked
   * @return clickedDts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date/time that the email was clicked")

  public String getClickedDts() {
    return clickedDts;
  }


  public void setClickedDts(String clickedDts) {
    this.clickedDts = clickedDts;
  }


  public AutoOrderEmail delivered(Boolean delivered) {
    
    this.delivered = delivered;
    return this;
  }

   /**
   * Get delivered
   * @return delivered
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDelivered() {
    return delivered;
  }


  public void setDelivered(Boolean delivered) {
    this.delivered = delivered;
  }


  public AutoOrderEmail deliveryDts(String deliveryDts) {
    
    this.deliveryDts = deliveryDts;
    return this;
  }

   /**
   * Date/time that the email was delivered
   * @return deliveryDts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date/time that the email was delivered")

  public String getDeliveryDts() {
    return deliveryDts;
  }


  public void setDeliveryDts(String deliveryDts) {
    this.deliveryDts = deliveryDts;
  }


  public AutoOrderEmail email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Email")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public AutoOrderEmail internal(Boolean internal) {
    
    this.internal = internal;
    return this;
  }

   /**
   * Get internal
   * @return internal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getInternal() {
    return internal;
  }


  public void setInternal(Boolean internal) {
    this.internal = internal;
  }


  public AutoOrderEmail messageId(String messageId) {
    
    this.messageId = messageId;
    return this;
  }

   /**
   * Get messageId
   * @return messageId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMessageId() {
    return messageId;
  }


  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }


  public AutoOrderEmail opened(Boolean opened) {
    
    this.opened = opened;
    return this;
  }

   /**
   * Get opened
   * @return opened
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getOpened() {
    return opened;
  }


  public void setOpened(Boolean opened) {
    this.opened = opened;
  }


  public AutoOrderEmail openedDts(String openedDts) {
    
    this.openedDts = openedDts;
    return this;
  }

   /**
   * Date/time that the email was opened
   * @return openedDts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date/time that the email was opened")

  public String getOpenedDts() {
    return openedDts;
  }


  public void setOpenedDts(String openedDts) {
    this.openedDts = openedDts;
  }


  public AutoOrderEmail reportingMta(String reportingMta) {
    
    this.reportingMta = reportingMta;
    return this;
  }

   /**
   * Get reportingMta
   * @return reportingMta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReportingMta() {
    return reportingMta;
  }


  public void setReportingMta(String reportingMta) {
    this.reportingMta = reportingMta;
  }


  public AutoOrderEmail sendDts(String sendDts) {
    
    this.sendDts = sendDts;
    return this;
  }

   /**
   * Date/time that the email was sent
   * @return sendDts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date/time that the email was sent")

  public String getSendDts() {
    return sendDts;
  }


  public void setSendDts(String sendDts) {
    this.sendDts = sendDts;
  }


  public AutoOrderEmail skipReason(String skipReason) {
    
    this.skipReason = skipReason;
    return this;
  }

   /**
   * Get skipReason
   * @return skipReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSkipReason() {
    return skipReason;
  }


  public void setSkipReason(String skipReason) {
    this.skipReason = skipReason;
  }


  public AutoOrderEmail skipped(Boolean skipped) {
    
    this.skipped = skipped;
    return this;
  }

   /**
   * Get skipped
   * @return skipped
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSkipped() {
    return skipped;
  }


  public void setSkipped(Boolean skipped) {
    this.skipped = skipped;
  }


  public AutoOrderEmail smtpResponse(String smtpResponse) {
    
    this.smtpResponse = smtpResponse;
    return this;
  }

   /**
   * Get smtpResponse
   * @return smtpResponse
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSmtpResponse() {
    return smtpResponse;
  }


  public void setSmtpResponse(String smtpResponse) {
    this.smtpResponse = smtpResponse;
  }


  public AutoOrderEmail subject(String subject) {
    
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubject() {
    return subject;
  }


  public void setSubject(String subject) {
    this.subject = subject;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoOrderEmail autoOrderEmail = (AutoOrderEmail) o;
    return Objects.equals(this.bounceDiagnosticCode, autoOrderEmail.bounceDiagnosticCode) &&
        Objects.equals(this.bounceDts, autoOrderEmail.bounceDts) &&
        Objects.equals(this.bounceSubType, autoOrderEmail.bounceSubType) &&
        Objects.equals(this.bounceType, autoOrderEmail.bounceType) &&
        Objects.equals(this.clicked, autoOrderEmail.clicked) &&
        Objects.equals(this.clickedDts, autoOrderEmail.clickedDts) &&
        Objects.equals(this.delivered, autoOrderEmail.delivered) &&
        Objects.equals(this.deliveryDts, autoOrderEmail.deliveryDts) &&
        Objects.equals(this.email, autoOrderEmail.email) &&
        Objects.equals(this.internal, autoOrderEmail.internal) &&
        Objects.equals(this.messageId, autoOrderEmail.messageId) &&
        Objects.equals(this.opened, autoOrderEmail.opened) &&
        Objects.equals(this.openedDts, autoOrderEmail.openedDts) &&
        Objects.equals(this.reportingMta, autoOrderEmail.reportingMta) &&
        Objects.equals(this.sendDts, autoOrderEmail.sendDts) &&
        Objects.equals(this.skipReason, autoOrderEmail.skipReason) &&
        Objects.equals(this.skipped, autoOrderEmail.skipped) &&
        Objects.equals(this.smtpResponse, autoOrderEmail.smtpResponse) &&
        Objects.equals(this.subject, autoOrderEmail.subject);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bounceDiagnosticCode, bounceDts, bounceSubType, bounceType, clicked, clickedDts, delivered, deliveryDts, email, internal, messageId, opened, openedDts, reportingMta, sendDts, skipReason, skipped, smtpResponse, subject);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoOrderEmail {\n");
    sb.append("    bounceDiagnosticCode: ").append(toIndentedString(bounceDiagnosticCode)).append("\n");
    sb.append("    bounceDts: ").append(toIndentedString(bounceDts)).append("\n");
    sb.append("    bounceSubType: ").append(toIndentedString(bounceSubType)).append("\n");
    sb.append("    bounceType: ").append(toIndentedString(bounceType)).append("\n");
    sb.append("    clicked: ").append(toIndentedString(clicked)).append("\n");
    sb.append("    clickedDts: ").append(toIndentedString(clickedDts)).append("\n");
    sb.append("    delivered: ").append(toIndentedString(delivered)).append("\n");
    sb.append("    deliveryDts: ").append(toIndentedString(deliveryDts)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    internal: ").append(toIndentedString(internal)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    opened: ").append(toIndentedString(opened)).append("\n");
    sb.append("    openedDts: ").append(toIndentedString(openedDts)).append("\n");
    sb.append("    reportingMta: ").append(toIndentedString(reportingMta)).append("\n");
    sb.append("    sendDts: ").append(toIndentedString(sendDts)).append("\n");
    sb.append("    skipReason: ").append(toIndentedString(skipReason)).append("\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    smtpResponse: ").append(toIndentedString(smtpResponse)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bounce_diagnostic_code");
    openapiFields.add("bounce_dts");
    openapiFields.add("bounce_sub_type");
    openapiFields.add("bounce_type");
    openapiFields.add("clicked");
    openapiFields.add("clicked_dts");
    openapiFields.add("delivered");
    openapiFields.add("delivery_dts");
    openapiFields.add("email");
    openapiFields.add("internal");
    openapiFields.add("message_id");
    openapiFields.add("opened");
    openapiFields.add("opened_dts");
    openapiFields.add("reporting_mta");
    openapiFields.add("send_dts");
    openapiFields.add("skip_reason");
    openapiFields.add("skipped");
    openapiFields.add("smtp_response");
    openapiFields.add("subject");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AutoOrderEmail
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (AutoOrderEmail.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in AutoOrderEmail is not found in the empty JSON string", AutoOrderEmail.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!AutoOrderEmail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AutoOrderEmail` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("bounce_diagnostic_code") != null && !jsonObj.get("bounce_diagnostic_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bounce_diagnostic_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bounce_diagnostic_code").toString()));
      }
      if (jsonObj.get("bounce_dts") != null && !jsonObj.get("bounce_dts").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bounce_dts` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bounce_dts").toString()));
      }
      if (jsonObj.get("bounce_sub_type") != null && !jsonObj.get("bounce_sub_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bounce_sub_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bounce_sub_type").toString()));
      }
      if (jsonObj.get("bounce_type") != null && !jsonObj.get("bounce_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bounce_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bounce_type").toString()));
      }
      if (jsonObj.get("clicked_dts") != null && !jsonObj.get("clicked_dts").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `clicked_dts` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clicked_dts").toString()));
      }
      if (jsonObj.get("delivery_dts") != null && !jsonObj.get("delivery_dts").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `delivery_dts` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivery_dts").toString()));
      }
      if (jsonObj.get("email") != null && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if (jsonObj.get("message_id") != null && !jsonObj.get("message_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message_id").toString()));
      }
      if (jsonObj.get("opened_dts") != null && !jsonObj.get("opened_dts").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `opened_dts` to be a primitive type in the JSON string but got `%s`", jsonObj.get("opened_dts").toString()));
      }
      if (jsonObj.get("reporting_mta") != null && !jsonObj.get("reporting_mta").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reporting_mta` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reporting_mta").toString()));
      }
      if (jsonObj.get("send_dts") != null && !jsonObj.get("send_dts").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `send_dts` to be a primitive type in the JSON string but got `%s`", jsonObj.get("send_dts").toString()));
      }
      if (jsonObj.get("skip_reason") != null && !jsonObj.get("skip_reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `skip_reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("skip_reason").toString()));
      }
      if (jsonObj.get("smtp_response") != null && !jsonObj.get("smtp_response").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `smtp_response` to be a primitive type in the JSON string but got `%s`", jsonObj.get("smtp_response").toString()));
      }
      if (jsonObj.get("subject") != null && !jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AutoOrderEmail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AutoOrderEmail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AutoOrderEmail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AutoOrderEmail.class));

       return (TypeAdapter<T>) new TypeAdapter<AutoOrderEmail>() {
           @Override
           public void write(JsonWriter out, AutoOrderEmail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AutoOrderEmail read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AutoOrderEmail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AutoOrderEmail
  * @throws IOException if the JSON string is invalid with respect to AutoOrderEmail
  */
  public static AutoOrderEmail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AutoOrderEmail.class);
  }

 /**
  * Convert an instance of AutoOrderEmail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

