/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * ConversationAgentTestSessionRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-04T15:59:36.528-04:00[America/Indianapolis]")
public class ConversationAgentTestSessionRequest {
  public static final String SERIALIZED_NAME_CUSTOMER_PROFILE_OID = "customer_profile_oid";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_PROFILE_OID)
  private Integer customerProfileOid;

  public static final String SERIALIZED_NAME_QUESTION = "question";
  @SerializedName(SERIALIZED_NAME_QUESTION)
  private String question;

  public static final String SERIALIZED_NAME_QUEUE_NAME = "queue_name";
  @SerializedName(SERIALIZED_NAME_QUEUE_NAME)
  private String queueName;

  public static final String SERIALIZED_NAME_STOREFRONT_HOST_NAME = "storefront_host_name";
  @SerializedName(SERIALIZED_NAME_STOREFRONT_HOST_NAME)
  private String storefrontHostName;

  public ConversationAgentTestSessionRequest() { 
  }

  public ConversationAgentTestSessionRequest customerProfileOid(Integer customerProfileOid) {
    
    this.customerProfileOid = customerProfileOid;
    return this;
  }

   /**
   * Customer profile to converse as.  The cart is established as a soft login for this customer, so the agent sees their real order history.
   * @return customerProfileOid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Customer profile to converse as.  The cart is established as a soft login for this customer, so the agent sees their real order history.")

  public Integer getCustomerProfileOid() {
    return customerProfileOid;
  }


  public void setCustomerProfileOid(Integer customerProfileOid) {
    this.customerProfileOid = customerProfileOid;
  }


  public ConversationAgentTestSessionRequest question(String question) {
    
    this.question = question;
    return this;
  }

   /**
   * Optional opening question, the same way a customer types one before joining the queue.
   * @return question
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional opening question, the same way a customer types one before joining the queue.")

  public String getQuestion() {
    return question;
  }


  public void setQuestion(String question) {
    this.question = question;
  }


  public ConversationAgentTestSessionRequest queueName(String queueName) {
    
    this.queueName = queueName;
    return this;
  }

   /**
   * Webchat queue to join.  The agent is selected explicitly, so this does not have to be a queue the agent is assigned to.
   * @return queueName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Webchat queue to join.  The agent is selected explicitly, so this does not have to be a queue the agent is assigned to.")

  public String getQueueName() {
    return queueName;
  }


  public void setQueueName(String queueName) {
    this.queueName = queueName;
  }


  public ConversationAgentTestSessionRequest storefrontHostName(String storefrontHostName) {
    
    this.storefrontHostName = storefrontHostName;
    return this;
  }

   /**
   * Host name of the storefront to test against, with no protocol prefix.  Determines which catalog the agent searches.
   * @return storefrontHostName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Host name of the storefront to test against, with no protocol prefix.  Determines which catalog the agent searches.")

  public String getStorefrontHostName() {
    return storefrontHostName;
  }


  public void setStorefrontHostName(String storefrontHostName) {
    this.storefrontHostName = storefrontHostName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationAgentTestSessionRequest conversationAgentTestSessionRequest = (ConversationAgentTestSessionRequest) o;
    return Objects.equals(this.customerProfileOid, conversationAgentTestSessionRequest.customerProfileOid) &&
        Objects.equals(this.question, conversationAgentTestSessionRequest.question) &&
        Objects.equals(this.queueName, conversationAgentTestSessionRequest.queueName) &&
        Objects.equals(this.storefrontHostName, conversationAgentTestSessionRequest.storefrontHostName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerProfileOid, question, queueName, storefrontHostName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationAgentTestSessionRequest {\n");
    sb.append("    customerProfileOid: ").append(toIndentedString(customerProfileOid)).append("\n");
    sb.append("    question: ").append(toIndentedString(question)).append("\n");
    sb.append("    queueName: ").append(toIndentedString(queueName)).append("\n");
    sb.append("    storefrontHostName: ").append(toIndentedString(storefrontHostName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("customer_profile_oid");
    openapiFields.add("question");
    openapiFields.add("queue_name");
    openapiFields.add("storefront_host_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ConversationAgentTestSessionRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ConversationAgentTestSessionRequest.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConversationAgentTestSessionRequest is not found in the empty JSON string", ConversationAgentTestSessionRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ConversationAgentTestSessionRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConversationAgentTestSessionRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("question") != null && !jsonObj.get("question").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `question` to be a primitive type in the JSON string but got `%s`", jsonObj.get("question").toString()));
      }
      if (jsonObj.get("queue_name") != null && !jsonObj.get("queue_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `queue_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("queue_name").toString()));
      }
      if (jsonObj.get("storefront_host_name") != null && !jsonObj.get("storefront_host_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `storefront_host_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("storefront_host_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConversationAgentTestSessionRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConversationAgentTestSessionRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConversationAgentTestSessionRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConversationAgentTestSessionRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ConversationAgentTestSessionRequest>() {
           @Override
           public void write(JsonWriter out, ConversationAgentTestSessionRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConversationAgentTestSessionRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ConversationAgentTestSessionRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ConversationAgentTestSessionRequest
  * @throws IOException if the JSON string is invalid with respect to ConversationAgentTestSessionRequest
  */
  public static ConversationAgentTestSessionRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConversationAgentTestSessionRequest.class);
  }

 /**
  * Convert an instance of ConversationAgentTestSessionRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

