/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConversationPbxCallAiWhisper
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2026-02-02T10:35:09.447-05:00")



public class ConversationPbxCallAiWhisper {
  @SerializedName("message")
  private String message = null;

  @SerializedName("priority")
  private String priority = null;

  @SerializedName("whisper_uuid")
  private String whisperUuid = null;

  @SerializedName("whispered_at_dts")
  private String whisperedAtDts = null;

  public ConversationPbxCallAiWhisper message(String message) {
    this.message = message;
    return this;
  }

   /**
   * The whisper message content
   * @return message
  **/
  @ApiModelProperty(value = "The whisper message content")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ConversationPbxCallAiWhisper priority(String priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Priority level of the whisper
   * @return priority
  **/
  @ApiModelProperty(value = "Priority level of the whisper")
  public String getPriority() {
    return priority;
  }

  public void setPriority(String priority) {
    this.priority = priority;
  }

  public ConversationPbxCallAiWhisper whisperUuid(String whisperUuid) {
    this.whisperUuid = whisperUuid;
    return this;
  }

   /**
   * Unique identifier for this whisper
   * @return whisperUuid
  **/
  @ApiModelProperty(value = "Unique identifier for this whisper")
  public String getWhisperUuid() {
    return whisperUuid;
  }

  public void setWhisperUuid(String whisperUuid) {
    this.whisperUuid = whisperUuid;
  }

  public ConversationPbxCallAiWhisper whisperedAtDts(String whisperedAtDts) {
    this.whisperedAtDts = whisperedAtDts;
    return this;
  }

   /**
   * Timestamp when the whisper was sent
   * @return whisperedAtDts
  **/
  @ApiModelProperty(value = "Timestamp when the whisper was sent")
  public String getWhisperedAtDts() {
    return whisperedAtDts;
  }

  public void setWhisperedAtDts(String whisperedAtDts) {
    this.whisperedAtDts = whisperedAtDts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationPbxCallAiWhisper conversationPbxCallAiWhisper = (ConversationPbxCallAiWhisper) o;
    return Objects.equals(this.message, conversationPbxCallAiWhisper.message) &&
        Objects.equals(this.priority, conversationPbxCallAiWhisper.priority) &&
        Objects.equals(this.whisperUuid, conversationPbxCallAiWhisper.whisperUuid) &&
        Objects.equals(this.whisperedAtDts, conversationPbxCallAiWhisper.whisperedAtDts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, priority, whisperUuid, whisperedAtDts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationPbxCallAiWhisper {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    whisperUuid: ").append(toIndentedString(whisperUuid)).append("\n");
    sb.append("    whisperedAtDts: ").append(toIndentedString(whisperedAtDts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

