/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * ConversationPbxCallFinancial
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-02T13:31:12.803-05:00[America/Indianapolis]")
public class ConversationPbxCallFinancial {
  public static final String SERIALIZED_NAME_AI_AGENT_BILLED_MINUTES = "ai_agent_billed_minutes";
  @SerializedName(SERIALIZED_NAME_AI_AGENT_BILLED_MINUTES)
  private BigDecimal aiAgentBilledMinutes;

  public static final String SERIALIZED_NAME_AI_AGENT_COST = "ai_agent_cost";
  @SerializedName(SERIALIZED_NAME_AI_AGENT_COST)
  private BigDecimal aiAgentCost;

  public static final String SERIALIZED_NAME_AI_AGENT_COST_CURRENCY = "ai_agent_cost_currency";
  @SerializedName(SERIALIZED_NAME_AI_AGENT_COST_CURRENCY)
  private String aiAgentCostCurrency;

  public static final String SERIALIZED_NAME_CALL_CURRENCY = "call_currency";
  @SerializedName(SERIALIZED_NAME_CALL_CURRENCY)
  private String callCurrency;

  public static final String SERIALIZED_NAME_CALL_PRICE = "call_price";
  @SerializedName(SERIALIZED_NAME_CALL_PRICE)
  private BigDecimal callPrice;

  public static final String SERIALIZED_NAME_CALL_PRICE_ESTIMATED = "call_price_estimated";
  @SerializedName(SERIALIZED_NAME_CALL_PRICE_ESTIMATED)
  private Boolean callPriceEstimated;

  public static final String SERIALIZED_NAME_TRANSCRIPTION_COST = "transcription_cost";
  @SerializedName(SERIALIZED_NAME_TRANSCRIPTION_COST)
  private BigDecimal transcriptionCost;

  public ConversationPbxCallFinancial() { 
  }

  public ConversationPbxCallFinancial aiAgentBilledMinutes(BigDecimal aiAgentBilledMinutes) {
    
    this.aiAgentBilledMinutes = aiAgentBilledMinutes;
    return this;
  }

   /**
   * Total AI agent billed minutes for this call
   * @return aiAgentBilledMinutes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total AI agent billed minutes for this call")

  public BigDecimal getAiAgentBilledMinutes() {
    return aiAgentBilledMinutes;
  }


  public void setAiAgentBilledMinutes(BigDecimal aiAgentBilledMinutes) {
    this.aiAgentBilledMinutes = aiAgentBilledMinutes;
  }


  public ConversationPbxCallFinancial aiAgentCost(BigDecimal aiAgentCost) {
    
    this.aiAgentCost = aiAgentCost;
    return this;
  }

   /**
   * Total AI agent cost for this call
   * @return aiAgentCost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total AI agent cost for this call")

  public BigDecimal getAiAgentCost() {
    return aiAgentCost;
  }


  public void setAiAgentCost(BigDecimal aiAgentCost) {
    this.aiAgentCost = aiAgentCost;
  }


  public ConversationPbxCallFinancial aiAgentCostCurrency(String aiAgentCostCurrency) {
    
    this.aiAgentCostCurrency = aiAgentCostCurrency;
    return this;
  }

   /**
   * Currency for AI agent cost
   * @return aiAgentCostCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Currency for AI agent cost")

  public String getAiAgentCostCurrency() {
    return aiAgentCostCurrency;
  }


  public void setAiAgentCostCurrency(String aiAgentCostCurrency) {
    this.aiAgentCostCurrency = aiAgentCostCurrency;
  }


  public ConversationPbxCallFinancial callCurrency(String callCurrency) {
    
    this.callCurrency = callCurrency;
    return this;
  }

   /**
   * Currency for call price (default USD)
   * @return callCurrency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Currency for call price (default USD)")

  public String getCallCurrency() {
    return callCurrency;
  }


  public void setCallCurrency(String callCurrency) {
    this.callCurrency = callCurrency;
  }


  public ConversationPbxCallFinancial callPrice(BigDecimal callPrice) {
    
    this.callPrice = callPrice;
    return this;
  }

   /**
   * Twilio call cost
   * @return callPrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Twilio call cost")

  public BigDecimal getCallPrice() {
    return callPrice;
  }


  public void setCallPrice(BigDecimal callPrice) {
    this.callPrice = callPrice;
  }


  public ConversationPbxCallFinancial callPriceEstimated(Boolean callPriceEstimated) {
    
    this.callPriceEstimated = callPriceEstimated;
    return this;
  }

   /**
   * True if call price is a fallback-rate estimate, false if Twilio-confirmed
   * @return callPriceEstimated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "True if call price is a fallback-rate estimate, false if Twilio-confirmed")

  public Boolean getCallPriceEstimated() {
    return callPriceEstimated;
  }


  public void setCallPriceEstimated(Boolean callPriceEstimated) {
    this.callPriceEstimated = callPriceEstimated;
  }


  public ConversationPbxCallFinancial transcriptionCost(BigDecimal transcriptionCost) {
    
    this.transcriptionCost = transcriptionCost;
    return this;
  }

   /**
   * AWS Transcribe transcription cost
   * @return transcriptionCost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "AWS Transcribe transcription cost")

  public BigDecimal getTranscriptionCost() {
    return transcriptionCost;
  }


  public void setTranscriptionCost(BigDecimal transcriptionCost) {
    this.transcriptionCost = transcriptionCost;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationPbxCallFinancial conversationPbxCallFinancial = (ConversationPbxCallFinancial) o;
    return Objects.equals(this.aiAgentBilledMinutes, conversationPbxCallFinancial.aiAgentBilledMinutes) &&
        Objects.equals(this.aiAgentCost, conversationPbxCallFinancial.aiAgentCost) &&
        Objects.equals(this.aiAgentCostCurrency, conversationPbxCallFinancial.aiAgentCostCurrency) &&
        Objects.equals(this.callCurrency, conversationPbxCallFinancial.callCurrency) &&
        Objects.equals(this.callPrice, conversationPbxCallFinancial.callPrice) &&
        Objects.equals(this.callPriceEstimated, conversationPbxCallFinancial.callPriceEstimated) &&
        Objects.equals(this.transcriptionCost, conversationPbxCallFinancial.transcriptionCost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aiAgentBilledMinutes, aiAgentCost, aiAgentCostCurrency, callCurrency, callPrice, callPriceEstimated, transcriptionCost);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationPbxCallFinancial {\n");
    sb.append("    aiAgentBilledMinutes: ").append(toIndentedString(aiAgentBilledMinutes)).append("\n");
    sb.append("    aiAgentCost: ").append(toIndentedString(aiAgentCost)).append("\n");
    sb.append("    aiAgentCostCurrency: ").append(toIndentedString(aiAgentCostCurrency)).append("\n");
    sb.append("    callCurrency: ").append(toIndentedString(callCurrency)).append("\n");
    sb.append("    callPrice: ").append(toIndentedString(callPrice)).append("\n");
    sb.append("    callPriceEstimated: ").append(toIndentedString(callPriceEstimated)).append("\n");
    sb.append("    transcriptionCost: ").append(toIndentedString(transcriptionCost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ai_agent_billed_minutes");
    openapiFields.add("ai_agent_cost");
    openapiFields.add("ai_agent_cost_currency");
    openapiFields.add("call_currency");
    openapiFields.add("call_price");
    openapiFields.add("call_price_estimated");
    openapiFields.add("transcription_cost");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ConversationPbxCallFinancial
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ConversationPbxCallFinancial.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConversationPbxCallFinancial is not found in the empty JSON string", ConversationPbxCallFinancial.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ConversationPbxCallFinancial.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConversationPbxCallFinancial` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("ai_agent_cost_currency") != null && !jsonObj.get("ai_agent_cost_currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ai_agent_cost_currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ai_agent_cost_currency").toString()));
      }
      if (jsonObj.get("call_currency") != null && !jsonObj.get("call_currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `call_currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("call_currency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConversationPbxCallFinancial.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConversationPbxCallFinancial' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConversationPbxCallFinancial> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConversationPbxCallFinancial.class));

       return (TypeAdapter<T>) new TypeAdapter<ConversationPbxCallFinancial>() {
           @Override
           public void write(JsonWriter out, ConversationPbxCallFinancial value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConversationPbxCallFinancial read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ConversationPbxCallFinancial given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ConversationPbxCallFinancial
  * @throws IOException if the JSON string is invalid with respect to ConversationPbxCallFinancial
  */
  public static ConversationPbxCallFinancial fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConversationPbxCallFinancial.class);
  }

 /**
  * Convert an instance of ConversationPbxCallFinancial to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

