/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConversationSearchRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2026-02-12T16:08:36.126-05:00")



public class ConversationSearchRequest {
  @SerializedName("date_end")
  private String dateEnd = null;

  @SerializedName("date_start")
  private String dateStart = null;

  @SerializedName("email_filter")
  private String emailFilter = null;

  @SerializedName("language_filter")
  private String languageFilter = null;

  @SerializedName("medium_filter")
  private String mediumFilter = null;

  @SerializedName("order_by_newest")
  private Boolean orderByNewest = null;

  @SerializedName("order_by_oldest")
  private Boolean orderByOldest = null;

  @SerializedName("range_begin")
  private Integer rangeBegin = null;

  @SerializedName("range_end")
  private Integer rangeEnd = null;

  @SerializedName("sms_phone_number_filter")
  private String smsPhoneNumberFilter = null;

  @SerializedName("text_search")
  private String textSearch = null;

  @SerializedName("visible_filter")
  private Boolean visibleFilter = null;

  public ConversationSearchRequest dateEnd(String dateEnd) {
    this.dateEnd = dateEnd;
    return this;
  }

   /**
   * End of the range
   * @return dateEnd
  **/
  @ApiModelProperty(value = "End of the range")
  public String getDateEnd() {
    return dateEnd;
  }

  public void setDateEnd(String dateEnd) {
    this.dateEnd = dateEnd;
  }

  public ConversationSearchRequest dateStart(String dateStart) {
    this.dateStart = dateStart;
    return this;
  }

   /**
   * Start of the range
   * @return dateStart
  **/
  @ApiModelProperty(value = "Start of the range")
  public String getDateStart() {
    return dateStart;
  }

  public void setDateStart(String dateStart) {
    this.dateStart = dateStart;
  }

  public ConversationSearchRequest emailFilter(String emailFilter) {
    this.emailFilter = emailFilter;
    return this;
  }

   /**
   * Get emailFilter
   * @return emailFilter
  **/
  @ApiModelProperty(value = "")
  public String getEmailFilter() {
    return emailFilter;
  }

  public void setEmailFilter(String emailFilter) {
    this.emailFilter = emailFilter;
  }

  public ConversationSearchRequest languageFilter(String languageFilter) {
    this.languageFilter = languageFilter;
    return this;
  }

   /**
   * Get languageFilter
   * @return languageFilter
  **/
  @ApiModelProperty(value = "")
  public String getLanguageFilter() {
    return languageFilter;
  }

  public void setLanguageFilter(String languageFilter) {
    this.languageFilter = languageFilter;
  }

  public ConversationSearchRequest mediumFilter(String mediumFilter) {
    this.mediumFilter = mediumFilter;
    return this;
  }

   /**
   * Get mediumFilter
   * @return mediumFilter
  **/
  @ApiModelProperty(value = "")
  public String getMediumFilter() {
    return mediumFilter;
  }

  public void setMediumFilter(String mediumFilter) {
    this.mediumFilter = mediumFilter;
  }

  public ConversationSearchRequest orderByNewest(Boolean orderByNewest) {
    this.orderByNewest = orderByNewest;
    return this;
  }

   /**
   * Get orderByNewest
   * @return orderByNewest
  **/
  @ApiModelProperty(value = "")
  public Boolean isOrderByNewest() {
    return orderByNewest;
  }

  public void setOrderByNewest(Boolean orderByNewest) {
    this.orderByNewest = orderByNewest;
  }

  public ConversationSearchRequest orderByOldest(Boolean orderByOldest) {
    this.orderByOldest = orderByOldest;
    return this;
  }

   /**
   * Get orderByOldest
   * @return orderByOldest
  **/
  @ApiModelProperty(value = "")
  public Boolean isOrderByOldest() {
    return orderByOldest;
  }

  public void setOrderByOldest(Boolean orderByOldest) {
    this.orderByOldest = orderByOldest;
  }

  public ConversationSearchRequest rangeBegin(Integer rangeBegin) {
    this.rangeBegin = rangeBegin;
    return this;
  }

   /**
   * Get rangeBegin
   * @return rangeBegin
  **/
  @ApiModelProperty(value = "")
  public Integer getRangeBegin() {
    return rangeBegin;
  }

  public void setRangeBegin(Integer rangeBegin) {
    this.rangeBegin = rangeBegin;
  }

  public ConversationSearchRequest rangeEnd(Integer rangeEnd) {
    this.rangeEnd = rangeEnd;
    return this;
  }

   /**
   * Get rangeEnd
   * @return rangeEnd
  **/
  @ApiModelProperty(value = "")
  public Integer getRangeEnd() {
    return rangeEnd;
  }

  public void setRangeEnd(Integer rangeEnd) {
    this.rangeEnd = rangeEnd;
  }

  public ConversationSearchRequest smsPhoneNumberFilter(String smsPhoneNumberFilter) {
    this.smsPhoneNumberFilter = smsPhoneNumberFilter;
    return this;
  }

   /**
   * Get smsPhoneNumberFilter
   * @return smsPhoneNumberFilter
  **/
  @ApiModelProperty(value = "")
  public String getSmsPhoneNumberFilter() {
    return smsPhoneNumberFilter;
  }

  public void setSmsPhoneNumberFilter(String smsPhoneNumberFilter) {
    this.smsPhoneNumberFilter = smsPhoneNumberFilter;
  }

  public ConversationSearchRequest textSearch(String textSearch) {
    this.textSearch = textSearch;
    return this;
  }

   /**
   * Get textSearch
   * @return textSearch
  **/
  @ApiModelProperty(value = "")
  public String getTextSearch() {
    return textSearch;
  }

  public void setTextSearch(String textSearch) {
    this.textSearch = textSearch;
  }

  public ConversationSearchRequest visibleFilter(Boolean visibleFilter) {
    this.visibleFilter = visibleFilter;
    return this;
  }

   /**
   * Get visibleFilter
   * @return visibleFilter
  **/
  @ApiModelProperty(value = "")
  public Boolean isVisibleFilter() {
    return visibleFilter;
  }

  public void setVisibleFilter(Boolean visibleFilter) {
    this.visibleFilter = visibleFilter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationSearchRequest conversationSearchRequest = (ConversationSearchRequest) o;
    return Objects.equals(this.dateEnd, conversationSearchRequest.dateEnd) &&
        Objects.equals(this.dateStart, conversationSearchRequest.dateStart) &&
        Objects.equals(this.emailFilter, conversationSearchRequest.emailFilter) &&
        Objects.equals(this.languageFilter, conversationSearchRequest.languageFilter) &&
        Objects.equals(this.mediumFilter, conversationSearchRequest.mediumFilter) &&
        Objects.equals(this.orderByNewest, conversationSearchRequest.orderByNewest) &&
        Objects.equals(this.orderByOldest, conversationSearchRequest.orderByOldest) &&
        Objects.equals(this.rangeBegin, conversationSearchRequest.rangeBegin) &&
        Objects.equals(this.rangeEnd, conversationSearchRequest.rangeEnd) &&
        Objects.equals(this.smsPhoneNumberFilter, conversationSearchRequest.smsPhoneNumberFilter) &&
        Objects.equals(this.textSearch, conversationSearchRequest.textSearch) &&
        Objects.equals(this.visibleFilter, conversationSearchRequest.visibleFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateEnd, dateStart, emailFilter, languageFilter, mediumFilter, orderByNewest, orderByOldest, rangeBegin, rangeEnd, smsPhoneNumberFilter, textSearch, visibleFilter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationSearchRequest {\n");
    
    sb.append("    dateEnd: ").append(toIndentedString(dateEnd)).append("\n");
    sb.append("    dateStart: ").append(toIndentedString(dateStart)).append("\n");
    sb.append("    emailFilter: ").append(toIndentedString(emailFilter)).append("\n");
    sb.append("    languageFilter: ").append(toIndentedString(languageFilter)).append("\n");
    sb.append("    mediumFilter: ").append(toIndentedString(mediumFilter)).append("\n");
    sb.append("    orderByNewest: ").append(toIndentedString(orderByNewest)).append("\n");
    sb.append("    orderByOldest: ").append(toIndentedString(orderByOldest)).append("\n");
    sb.append("    rangeBegin: ").append(toIndentedString(rangeBegin)).append("\n");
    sb.append("    rangeEnd: ").append(toIndentedString(rangeEnd)).append("\n");
    sb.append("    smsPhoneNumberFilter: ").append(toIndentedString(smsPhoneNumberFilter)).append("\n");
    sb.append("    textSearch: ").append(toIndentedString(textSearch)).append("\n");
    sb.append("    visibleFilter: ").append(toIndentedString(visibleFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

