/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EmailStepWaitingRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-02T10:19:41.023-05:00")
public class EmailStepWaitingRequest {
  @SerializedName("commseq_step_uuids")
  private List<String> commseqStepUuids = null;

  public EmailStepWaitingRequest commseqStepUuids(List<String> commseqStepUuids) {
    this.commseqStepUuids = commseqStepUuids;
    return this;
  }

  public EmailStepWaitingRequest addCommseqStepUuidsItem(String commseqStepUuidsItem) {
    if (this.commseqStepUuids == null) {
      this.commseqStepUuids = new ArrayList<String>();
    }
    this.commseqStepUuids.add(commseqStepUuidsItem);
    return this;
  }

   /**
   * Get commseqStepUuids
   * @return commseqStepUuids
  **/
  @ApiModelProperty(value = "")
  public List<String> getCommseqStepUuids() {
    return commseqStepUuids;
  }

  public void setCommseqStepUuids(List<String> commseqStepUuids) {
    this.commseqStepUuids = commseqStepUuids;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailStepWaitingRequest emailStepWaitingRequest = (EmailStepWaitingRequest) o;
    return Objects.equals(this.commseqStepUuids, emailStepWaitingRequest.commseqStepUuids);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commseqStepUuids);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailStepWaitingRequest {\n");
    
    sb.append("    commseqStepUuids: ").append(toIndentedString(commseqStepUuids)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

