/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * EmailSmsStat
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-20T12:50:59.354-04:00[America/Indianapolis]")
public class EmailSmsStat {
  public static final String SERIALIZED_NAME_CLICK_COUNT = "click_count";
  @SerializedName(SERIALIZED_NAME_CLICK_COUNT)
  private Integer clickCount;

  public static final String SERIALIZED_NAME_CLICK_COUNT_FORMATTED = "click_count_formatted";
  @SerializedName(SERIALIZED_NAME_CLICK_COUNT_FORMATTED)
  private String clickCountFormatted;

  public static final String SERIALIZED_NAME_CONVERSION_COUNT = "conversion_count";
  @SerializedName(SERIALIZED_NAME_CONVERSION_COUNT)
  private Integer conversionCount;

  public static final String SERIALIZED_NAME_CONVERSION_COUNT_FORMATTED = "conversion_count_formatted";
  @SerializedName(SERIALIZED_NAME_CONVERSION_COUNT_FORMATTED)
  private String conversionCountFormatted;

  public static final String SERIALIZED_NAME_DELETED = "deleted";
  @SerializedName(SERIALIZED_NAME_DELETED)
  private Boolean deleted;

  public static final String SERIALIZED_NAME_DELIVERED_COUNT = "delivered_count";
  @SerializedName(SERIALIZED_NAME_DELIVERED_COUNT)
  private Integer deliveredCount;

  public static final String SERIALIZED_NAME_DELIVERED_COUNT_FORMATTED = "delivered_count_formatted";
  @SerializedName(SERIALIZED_NAME_DELIVERED_COUNT_FORMATTED)
  private String deliveredCountFormatted;

  public static final String SERIALIZED_NAME_MERCHANT_ID = "merchant_id";
  @SerializedName(SERIALIZED_NAME_MERCHANT_ID)
  private String merchantId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ORDER_COUNT = "order_count";
  @SerializedName(SERIALIZED_NAME_ORDER_COUNT)
  private Integer orderCount;

  public static final String SERIALIZED_NAME_ORDER_COUNT_FORMATTED = "order_count_formatted";
  @SerializedName(SERIALIZED_NAME_ORDER_COUNT_FORMATTED)
  private String orderCountFormatted;

  public static final String SERIALIZED_NAME_PROFIT = "profit";
  @SerializedName(SERIALIZED_NAME_PROFIT)
  private BigDecimal profit;

  public static final String SERIALIZED_NAME_PROFIT_FORMATTED = "profit_formatted";
  @SerializedName(SERIALIZED_NAME_PROFIT_FORMATTED)
  private String profitFormatted;

  public static final String SERIALIZED_NAME_REVENUE = "revenue";
  @SerializedName(SERIALIZED_NAME_REVENUE)
  private BigDecimal revenue;

  public static final String SERIALIZED_NAME_REVENUE_FORMATTED = "revenue_formatted";
  @SerializedName(SERIALIZED_NAME_REVENUE_FORMATTED)
  private String revenueFormatted;

  public static final String SERIALIZED_NAME_SEND_COUNT = "send_count";
  @SerializedName(SERIALIZED_NAME_SEND_COUNT)
  private Integer sendCount;

  public static final String SERIALIZED_NAME_SEND_COUNT_FORMATTED = "send_count_formatted";
  @SerializedName(SERIALIZED_NAME_SEND_COUNT_FORMATTED)
  private String sendCountFormatted;

  public static final String SERIALIZED_NAME_SKIPPED_COUNT = "skipped_count";
  @SerializedName(SERIALIZED_NAME_SKIPPED_COUNT)
  private Integer skippedCount;

  public static final String SERIALIZED_NAME_SKIPPED_COUNT_FORMATTED = "skipped_count_formatted";
  @SerializedName(SERIALIZED_NAME_SKIPPED_COUNT_FORMATTED)
  private String skippedCountFormatted;

  public static final String SERIALIZED_NAME_STAT_TYPE = "stat_type";
  @SerializedName(SERIALIZED_NAME_STAT_TYPE)
  private String statType;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STATUS_DTS = "status_dts";
  @SerializedName(SERIALIZED_NAME_STATUS_DTS)
  private String statusDts;

  public static final String SERIALIZED_NAME_STEP_UUID = "step_uuid";
  @SerializedName(SERIALIZED_NAME_STEP_UUID)
  private String stepUuid;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private List<EmailSmsStat> steps = null;

  public static final String SERIALIZED_NAME_STOREFRONT_OID = "storefront_oid";
  @SerializedName(SERIALIZED_NAME_STOREFRONT_OID)
  private Integer storefrontOid;

  public static final String SERIALIZED_NAME_UNSUBSCRIBE_COUNT = "unsubscribe_count";
  @SerializedName(SERIALIZED_NAME_UNSUBSCRIBE_COUNT)
  private Integer unsubscribeCount;

  public static final String SERIALIZED_NAME_UNSUBSCRIBE_COUNT_FORMATTED = "unsubscribe_count_formatted";
  @SerializedName(SERIALIZED_NAME_UNSUBSCRIBE_COUNT_FORMATTED)
  private String unsubscribeCountFormatted;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  private String uuid;

  public static final String SERIALIZED_NAME_VIEW_COUNT = "view_count";
  @SerializedName(SERIALIZED_NAME_VIEW_COUNT)
  private Integer viewCount;

  public static final String SERIALIZED_NAME_VIEW_COUNT_FORMATTED = "view_count_formatted";
  @SerializedName(SERIALIZED_NAME_VIEW_COUNT_FORMATTED)
  private String viewCountFormatted;

  public EmailSmsStat() { 
  }

  public EmailSmsStat clickCount(Integer clickCount) {
    
    this.clickCount = clickCount;
    return this;
  }

   /**
   * Count of clicked emails
   * @return clickCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of clicked emails")

  public Integer getClickCount() {
    return clickCount;
  }


  public void setClickCount(Integer clickCount) {
    this.clickCount = clickCount;
  }


  public EmailSmsStat clickCountFormatted(String clickCountFormatted) {
    
    this.clickCountFormatted = clickCountFormatted;
    return this;
  }

   /**
   * Count of clicked emails, formatted
   * @return clickCountFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of clicked emails, formatted")

  public String getClickCountFormatted() {
    return clickCountFormatted;
  }


  public void setClickCountFormatted(String clickCountFormatted) {
    this.clickCountFormatted = clickCountFormatted;
  }


  public EmailSmsStat conversionCount(Integer conversionCount) {
    
    this.conversionCount = conversionCount;
    return this;
  }

   /**
   * Count of conversions
   * @return conversionCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of conversions")

  public Integer getConversionCount() {
    return conversionCount;
  }


  public void setConversionCount(Integer conversionCount) {
    this.conversionCount = conversionCount;
  }


  public EmailSmsStat conversionCountFormatted(String conversionCountFormatted) {
    
    this.conversionCountFormatted = conversionCountFormatted;
    return this;
  }

   /**
   * Count of conversions, formatted
   * @return conversionCountFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of conversions, formatted")

  public String getConversionCountFormatted() {
    return conversionCountFormatted;
  }


  public void setConversionCountFormatted(String conversionCountFormatted) {
    this.conversionCountFormatted = conversionCountFormatted;
  }


  public EmailSmsStat deleted(Boolean deleted) {
    
    this.deleted = deleted;
    return this;
  }

   /**
   * True if campaign/flow has been archived
   * @return deleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "True if campaign/flow has been archived")

  public Boolean getDeleted() {
    return deleted;
  }


  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  public EmailSmsStat deliveredCount(Integer deliveredCount) {
    
    this.deliveredCount = deliveredCount;
    return this;
  }

   /**
   * Count of delivered emails
   * @return deliveredCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of delivered emails")

  public Integer getDeliveredCount() {
    return deliveredCount;
  }


  public void setDeliveredCount(Integer deliveredCount) {
    this.deliveredCount = deliveredCount;
  }


  public EmailSmsStat deliveredCountFormatted(String deliveredCountFormatted) {
    
    this.deliveredCountFormatted = deliveredCountFormatted;
    return this;
  }

   /**
   * Count of delivered emails, formatted
   * @return deliveredCountFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of delivered emails, formatted")

  public String getDeliveredCountFormatted() {
    return deliveredCountFormatted;
  }


  public void setDeliveredCountFormatted(String deliveredCountFormatted) {
    this.deliveredCountFormatted = deliveredCountFormatted;
  }


  public EmailSmsStat merchantId(String merchantId) {
    
    this.merchantId = merchantId;
    return this;
  }

   /**
   * Merchant ID
   * @return merchantId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Merchant ID")

  public String getMerchantId() {
    return merchantId;
  }


  public void setMerchantId(String merchantId) {
    this.merchantId = merchantId;
  }


  public EmailSmsStat name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * List or segment name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List or segment name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public EmailSmsStat orderCount(Integer orderCount) {
    
    this.orderCount = orderCount;
    return this;
  }

   /**
   * Count of orders
   * @return orderCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of orders")

  public Integer getOrderCount() {
    return orderCount;
  }


  public void setOrderCount(Integer orderCount) {
    this.orderCount = orderCount;
  }


  public EmailSmsStat orderCountFormatted(String orderCountFormatted) {
    
    this.orderCountFormatted = orderCountFormatted;
    return this;
  }

   /**
   * Count of orders, formatted
   * @return orderCountFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of orders, formatted")

  public String getOrderCountFormatted() {
    return orderCountFormatted;
  }


  public void setOrderCountFormatted(String orderCountFormatted) {
    this.orderCountFormatted = orderCountFormatted;
  }


  public EmailSmsStat profit(BigDecimal profit) {
    
    this.profit = profit;
    return this;
  }

   /**
   * Profit
   * @return profit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Profit")

  public BigDecimal getProfit() {
    return profit;
  }


  public void setProfit(BigDecimal profit) {
    this.profit = profit;
  }


  public EmailSmsStat profitFormatted(String profitFormatted) {
    
    this.profitFormatted = profitFormatted;
    return this;
  }

   /**
   * Profit, formatted
   * @return profitFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Profit, formatted")

  public String getProfitFormatted() {
    return profitFormatted;
  }


  public void setProfitFormatted(String profitFormatted) {
    this.profitFormatted = profitFormatted;
  }


  public EmailSmsStat revenue(BigDecimal revenue) {
    
    this.revenue = revenue;
    return this;
  }

   /**
   * Revenue
   * @return revenue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Revenue")

  public BigDecimal getRevenue() {
    return revenue;
  }


  public void setRevenue(BigDecimal revenue) {
    this.revenue = revenue;
  }


  public EmailSmsStat revenueFormatted(String revenueFormatted) {
    
    this.revenueFormatted = revenueFormatted;
    return this;
  }

   /**
   * Revenue, formatted
   * @return revenueFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Revenue, formatted")

  public String getRevenueFormatted() {
    return revenueFormatted;
  }


  public void setRevenueFormatted(String revenueFormatted) {
    this.revenueFormatted = revenueFormatted;
  }


  public EmailSmsStat sendCount(Integer sendCount) {
    
    this.sendCount = sendCount;
    return this;
  }

   /**
   * Count of emails sent
   * @return sendCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of emails sent")

  public Integer getSendCount() {
    return sendCount;
  }


  public void setSendCount(Integer sendCount) {
    this.sendCount = sendCount;
  }


  public EmailSmsStat sendCountFormatted(String sendCountFormatted) {
    
    this.sendCountFormatted = sendCountFormatted;
    return this;
  }

   /**
   * Count of emails sent, formatted
   * @return sendCountFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of emails sent, formatted")

  public String getSendCountFormatted() {
    return sendCountFormatted;
  }


  public void setSendCountFormatted(String sendCountFormatted) {
    this.sendCountFormatted = sendCountFormatted;
  }


  public EmailSmsStat skippedCount(Integer skippedCount) {
    
    this.skippedCount = skippedCount;
    return this;
  }

   /**
   * Count of skipped emails
   * @return skippedCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of skipped emails")

  public Integer getSkippedCount() {
    return skippedCount;
  }


  public void setSkippedCount(Integer skippedCount) {
    this.skippedCount = skippedCount;
  }


  public EmailSmsStat skippedCountFormatted(String skippedCountFormatted) {
    
    this.skippedCountFormatted = skippedCountFormatted;
    return this;
  }

   /**
   * Count of skipped emails, formatted
   * @return skippedCountFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of skipped emails, formatted")

  public String getSkippedCountFormatted() {
    return skippedCountFormatted;
  }


  public void setSkippedCountFormatted(String skippedCountFormatted) {
    this.skippedCountFormatted = skippedCountFormatted;
  }


  public EmailSmsStat statType(String statType) {
    
    this.statType = statType;
    return this;
  }

   /**
   * Campaign, Flow or None (for anything else)
   * @return statType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Campaign, Flow or None (for anything else)")

  public String getStatType() {
    return statType;
  }


  public void setStatType(String statType) {
    this.statType = statType;
  }


  public EmailSmsStat status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status of campaign or flow
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Status of campaign or flow")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public EmailSmsStat statusDts(String statusDts) {
    
    this.statusDts = statusDts;
    return this;
  }

   /**
   * Status dts of campaign or flow
   * @return statusDts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Status dts of campaign or flow")

  public String getStatusDts() {
    return statusDts;
  }


  public void setStatusDts(String statusDts) {
    this.statusDts = statusDts;
  }


  public EmailSmsStat stepUuid(String stepUuid) {
    
    this.stepUuid = stepUuid;
    return this;
  }

   /**
   * Step UUID if the statistics are at the step/email level
   * @return stepUuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Step UUID if the statistics are at the step/email level")

  public String getStepUuid() {
    return stepUuid;
  }


  public void setStepUuid(String stepUuid) {
    this.stepUuid = stepUuid;
  }


  public EmailSmsStat steps(List<EmailSmsStat> steps) {
    
    this.steps = steps;
    return this;
  }

  public EmailSmsStat addStepsItem(EmailSmsStat stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<EmailSmsStat> getSteps() {
    return steps;
  }


  public void setSteps(List<EmailSmsStat> steps) {
    this.steps = steps;
  }


  public EmailSmsStat storefrontOid(Integer storefrontOid) {
    
    this.storefrontOid = storefrontOid;
    return this;
  }

   /**
   * Storefront oid
   * @return storefrontOid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Storefront oid")

  public Integer getStorefrontOid() {
    return storefrontOid;
  }


  public void setStorefrontOid(Integer storefrontOid) {
    this.storefrontOid = storefrontOid;
  }


  public EmailSmsStat unsubscribeCount(Integer unsubscribeCount) {
    
    this.unsubscribeCount = unsubscribeCount;
    return this;
  }

   /**
   * Count of emails classified as unsubscribe
   * @return unsubscribeCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of emails classified as unsubscribe")

  public Integer getUnsubscribeCount() {
    return unsubscribeCount;
  }


  public void setUnsubscribeCount(Integer unsubscribeCount) {
    this.unsubscribeCount = unsubscribeCount;
  }


  public EmailSmsStat unsubscribeCountFormatted(String unsubscribeCountFormatted) {
    
    this.unsubscribeCountFormatted = unsubscribeCountFormatted;
    return this;
  }

   /**
   * Count of emails classified as unsubscribe, formatted
   * @return unsubscribeCountFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of emails classified as unsubscribe, formatted")

  public String getUnsubscribeCountFormatted() {
    return unsubscribeCountFormatted;
  }


  public void setUnsubscribeCountFormatted(String unsubscribeCountFormatted) {
    this.unsubscribeCountFormatted = unsubscribeCountFormatted;
  }


  public EmailSmsStat uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * List/Segment uuid, or Flow/Campaign uuid depending on level of stat aggregation.
   * @return uuid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List/Segment uuid, or Flow/Campaign uuid depending on level of stat aggregation.")

  public String getUuid() {
    return uuid;
  }


  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public EmailSmsStat viewCount(Integer viewCount) {
    
    this.viewCount = viewCount;
    return this;
  }

   /**
   * Count of views
   * @return viewCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of views")

  public Integer getViewCount() {
    return viewCount;
  }


  public void setViewCount(Integer viewCount) {
    this.viewCount = viewCount;
  }


  public EmailSmsStat viewCountFormatted(String viewCountFormatted) {
    
    this.viewCountFormatted = viewCountFormatted;
    return this;
  }

   /**
   * Count of views, formatted
   * @return viewCountFormatted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Count of views, formatted")

  public String getViewCountFormatted() {
    return viewCountFormatted;
  }


  public void setViewCountFormatted(String viewCountFormatted) {
    this.viewCountFormatted = viewCountFormatted;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailSmsStat emailSmsStat = (EmailSmsStat) o;
    return Objects.equals(this.clickCount, emailSmsStat.clickCount) &&
        Objects.equals(this.clickCountFormatted, emailSmsStat.clickCountFormatted) &&
        Objects.equals(this.conversionCount, emailSmsStat.conversionCount) &&
        Objects.equals(this.conversionCountFormatted, emailSmsStat.conversionCountFormatted) &&
        Objects.equals(this.deleted, emailSmsStat.deleted) &&
        Objects.equals(this.deliveredCount, emailSmsStat.deliveredCount) &&
        Objects.equals(this.deliveredCountFormatted, emailSmsStat.deliveredCountFormatted) &&
        Objects.equals(this.merchantId, emailSmsStat.merchantId) &&
        Objects.equals(this.name, emailSmsStat.name) &&
        Objects.equals(this.orderCount, emailSmsStat.orderCount) &&
        Objects.equals(this.orderCountFormatted, emailSmsStat.orderCountFormatted) &&
        Objects.equals(this.profit, emailSmsStat.profit) &&
        Objects.equals(this.profitFormatted, emailSmsStat.profitFormatted) &&
        Objects.equals(this.revenue, emailSmsStat.revenue) &&
        Objects.equals(this.revenueFormatted, emailSmsStat.revenueFormatted) &&
        Objects.equals(this.sendCount, emailSmsStat.sendCount) &&
        Objects.equals(this.sendCountFormatted, emailSmsStat.sendCountFormatted) &&
        Objects.equals(this.skippedCount, emailSmsStat.skippedCount) &&
        Objects.equals(this.skippedCountFormatted, emailSmsStat.skippedCountFormatted) &&
        Objects.equals(this.statType, emailSmsStat.statType) &&
        Objects.equals(this.status, emailSmsStat.status) &&
        Objects.equals(this.statusDts, emailSmsStat.statusDts) &&
        Objects.equals(this.stepUuid, emailSmsStat.stepUuid) &&
        Objects.equals(this.steps, emailSmsStat.steps) &&
        Objects.equals(this.storefrontOid, emailSmsStat.storefrontOid) &&
        Objects.equals(this.unsubscribeCount, emailSmsStat.unsubscribeCount) &&
        Objects.equals(this.unsubscribeCountFormatted, emailSmsStat.unsubscribeCountFormatted) &&
        Objects.equals(this.uuid, emailSmsStat.uuid) &&
        Objects.equals(this.viewCount, emailSmsStat.viewCount) &&
        Objects.equals(this.viewCountFormatted, emailSmsStat.viewCountFormatted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clickCount, clickCountFormatted, conversionCount, conversionCountFormatted, deleted, deliveredCount, deliveredCountFormatted, merchantId, name, orderCount, orderCountFormatted, profit, profitFormatted, revenue, revenueFormatted, sendCount, sendCountFormatted, skippedCount, skippedCountFormatted, statType, status, statusDts, stepUuid, steps, storefrontOid, unsubscribeCount, unsubscribeCountFormatted, uuid, viewCount, viewCountFormatted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailSmsStat {\n");
    sb.append("    clickCount: ").append(toIndentedString(clickCount)).append("\n");
    sb.append("    clickCountFormatted: ").append(toIndentedString(clickCountFormatted)).append("\n");
    sb.append("    conversionCount: ").append(toIndentedString(conversionCount)).append("\n");
    sb.append("    conversionCountFormatted: ").append(toIndentedString(conversionCountFormatted)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    deliveredCount: ").append(toIndentedString(deliveredCount)).append("\n");
    sb.append("    deliveredCountFormatted: ").append(toIndentedString(deliveredCountFormatted)).append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    orderCount: ").append(toIndentedString(orderCount)).append("\n");
    sb.append("    orderCountFormatted: ").append(toIndentedString(orderCountFormatted)).append("\n");
    sb.append("    profit: ").append(toIndentedString(profit)).append("\n");
    sb.append("    profitFormatted: ").append(toIndentedString(profitFormatted)).append("\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("    revenueFormatted: ").append(toIndentedString(revenueFormatted)).append("\n");
    sb.append("    sendCount: ").append(toIndentedString(sendCount)).append("\n");
    sb.append("    sendCountFormatted: ").append(toIndentedString(sendCountFormatted)).append("\n");
    sb.append("    skippedCount: ").append(toIndentedString(skippedCount)).append("\n");
    sb.append("    skippedCountFormatted: ").append(toIndentedString(skippedCountFormatted)).append("\n");
    sb.append("    statType: ").append(toIndentedString(statType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusDts: ").append(toIndentedString(statusDts)).append("\n");
    sb.append("    stepUuid: ").append(toIndentedString(stepUuid)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    storefrontOid: ").append(toIndentedString(storefrontOid)).append("\n");
    sb.append("    unsubscribeCount: ").append(toIndentedString(unsubscribeCount)).append("\n");
    sb.append("    unsubscribeCountFormatted: ").append(toIndentedString(unsubscribeCountFormatted)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    viewCount: ").append(toIndentedString(viewCount)).append("\n");
    sb.append("    viewCountFormatted: ").append(toIndentedString(viewCountFormatted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("click_count");
    openapiFields.add("click_count_formatted");
    openapiFields.add("conversion_count");
    openapiFields.add("conversion_count_formatted");
    openapiFields.add("deleted");
    openapiFields.add("delivered_count");
    openapiFields.add("delivered_count_formatted");
    openapiFields.add("merchant_id");
    openapiFields.add("name");
    openapiFields.add("order_count");
    openapiFields.add("order_count_formatted");
    openapiFields.add("profit");
    openapiFields.add("profit_formatted");
    openapiFields.add("revenue");
    openapiFields.add("revenue_formatted");
    openapiFields.add("send_count");
    openapiFields.add("send_count_formatted");
    openapiFields.add("skipped_count");
    openapiFields.add("skipped_count_formatted");
    openapiFields.add("stat_type");
    openapiFields.add("status");
    openapiFields.add("status_dts");
    openapiFields.add("step_uuid");
    openapiFields.add("steps");
    openapiFields.add("storefront_oid");
    openapiFields.add("unsubscribe_count");
    openapiFields.add("unsubscribe_count_formatted");
    openapiFields.add("uuid");
    openapiFields.add("view_count");
    openapiFields.add("view_count_formatted");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EmailSmsStat
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (EmailSmsStat.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in EmailSmsStat is not found in the empty JSON string", EmailSmsStat.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!EmailSmsStat.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EmailSmsStat` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("click_count_formatted") != null && !jsonObj.get("click_count_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `click_count_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("click_count_formatted").toString()));
      }
      if (jsonObj.get("conversion_count_formatted") != null && !jsonObj.get("conversion_count_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `conversion_count_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("conversion_count_formatted").toString()));
      }
      if (jsonObj.get("delivered_count_formatted") != null && !jsonObj.get("delivered_count_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `delivered_count_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivered_count_formatted").toString()));
      }
      if (jsonObj.get("merchant_id") != null && !jsonObj.get("merchant_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchant_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchant_id").toString()));
      }
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("order_count_formatted") != null && !jsonObj.get("order_count_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `order_count_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_count_formatted").toString()));
      }
      if (jsonObj.get("profit_formatted") != null && !jsonObj.get("profit_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `profit_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("profit_formatted").toString()));
      }
      if (jsonObj.get("revenue_formatted") != null && !jsonObj.get("revenue_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `revenue_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("revenue_formatted").toString()));
      }
      if (jsonObj.get("send_count_formatted") != null && !jsonObj.get("send_count_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `send_count_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("send_count_formatted").toString()));
      }
      if (jsonObj.get("skipped_count_formatted") != null && !jsonObj.get("skipped_count_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `skipped_count_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("skipped_count_formatted").toString()));
      }
      if (jsonObj.get("stat_type") != null && !jsonObj.get("stat_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stat_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stat_type").toString()));
      }
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (jsonObj.get("status_dts") != null && !jsonObj.get("status_dts").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status_dts` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status_dts").toString()));
      }
      if (jsonObj.get("step_uuid") != null && !jsonObj.get("step_uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `step_uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("step_uuid").toString()));
      }
      JsonArray jsonArraysteps = jsonObj.getAsJsonArray("steps");
      if (jsonArraysteps != null) {
        // ensure the json data is an array
        if (!jsonObj.get("steps").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `steps` to be an array in the JSON string but got `%s`", jsonObj.get("steps").toString()));
        }

        // validate the optional field `steps` (array)
        for (int i = 0; i < jsonArraysteps.size(); i++) {
          EmailSmsStat.validateJsonObject(jsonArraysteps.get(i).getAsJsonObject());
        };
      }
      if (jsonObj.get("unsubscribe_count_formatted") != null && !jsonObj.get("unsubscribe_count_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unsubscribe_count_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unsubscribe_count_formatted").toString()));
      }
      if (jsonObj.get("uuid") != null && !jsonObj.get("uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uuid").toString()));
      }
      if (jsonObj.get("view_count_formatted") != null && !jsonObj.get("view_count_formatted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `view_count_formatted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("view_count_formatted").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EmailSmsStat.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EmailSmsStat' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EmailSmsStat> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EmailSmsStat.class));

       return (TypeAdapter<T>) new TypeAdapter<EmailSmsStat>() {
           @Override
           public void write(JsonWriter out, EmailSmsStat value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EmailSmsStat read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EmailSmsStat given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EmailSmsStat
  * @throws IOException if the JSON string is invalid with respect to EmailSmsStat
  */
  public static EmailSmsStat fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EmailSmsStat.class);
  }

 /**
  * Convert an instance of EmailSmsStat to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

