/**
 * UltraCart Rest API V2
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.ultracart.admin.v2.models.ItemContentAssignment;
import com.ultracart.admin.v2.models.ItemContentAttribute;
import com.ultracart.admin.v2.models.ItemContentMultimedia;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ItemContent
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T10:46:57.712-04:00")
public class ItemContent   {
  @SerializedName("assignments")
  private List<ItemContentAssignment> assignments = new ArrayList<ItemContentAssignment>();

  @SerializedName("attributes")
  private List<ItemContentAttribute> attributes = new ArrayList<ItemContentAttribute>();

  @SerializedName("exclude_from_search")
  private Boolean excludeFromSearch = null;

  @SerializedName("exclude_from_top_sellers")
  private Boolean excludeFromTopSellers = null;

  @SerializedName("extended_description")
  private String extendedDescription = null;

  @SerializedName("extended_description_translated_text_instance_oid")
  private Integer extendedDescriptionTranslatedTextInstanceOid = null;

  @SerializedName("multimedia")
  private List<ItemContentMultimedia> multimedia = new ArrayList<ItemContentMultimedia>();

  @SerializedName("new_item")
  private Boolean newItem = null;

  @SerializedName("new_item_end")
  private String newItemEnd = null;

  @SerializedName("new_item_start")
  private String newItemStart = null;

  @SerializedName("view_url")
  private String viewUrl = null;

  public ItemContent assignments(List<ItemContentAssignment> assignments) {
    this.assignments = assignments;
    return this;
  }

  public ItemContent addAssignmentsItem(ItemContentAssignment assignmentsItem) {
    this.assignments.add(assignmentsItem);
    return this;
  }

   /**
   * Get assignments
   * @return assignments
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ItemContentAssignment> getAssignments() {
    return assignments;
  }

  public void setAssignments(List<ItemContentAssignment> assignments) {
    this.assignments = assignments;
  }

  public ItemContent attributes(List<ItemContentAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ItemContent addAttributesItem(ItemContentAttribute attributesItem) {
    this.attributes.add(attributesItem);
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ItemContentAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<ItemContentAttribute> attributes) {
    this.attributes = attributes;
  }

  public ItemContent excludeFromSearch(Boolean excludeFromSearch) {
    this.excludeFromSearch = excludeFromSearch;
    return this;
  }

   /**
   * Get excludeFromSearch
   * @return excludeFromSearch
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getExcludeFromSearch() {
    return excludeFromSearch;
  }

  public void setExcludeFromSearch(Boolean excludeFromSearch) {
    this.excludeFromSearch = excludeFromSearch;
  }

  public ItemContent excludeFromTopSellers(Boolean excludeFromTopSellers) {
    this.excludeFromTopSellers = excludeFromTopSellers;
    return this;
  }

   /**
   * Get excludeFromTopSellers
   * @return excludeFromTopSellers
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getExcludeFromTopSellers() {
    return excludeFromTopSellers;
  }

  public void setExcludeFromTopSellers(Boolean excludeFromTopSellers) {
    this.excludeFromTopSellers = excludeFromTopSellers;
  }

  public ItemContent extendedDescription(String extendedDescription) {
    this.extendedDescription = extendedDescription;
    return this;
  }

   /**
   * Get extendedDescription
   * @return extendedDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExtendedDescription() {
    return extendedDescription;
  }

  public void setExtendedDescription(String extendedDescription) {
    this.extendedDescription = extendedDescription;
  }

  public ItemContent extendedDescriptionTranslatedTextInstanceOid(Integer extendedDescriptionTranslatedTextInstanceOid) {
    this.extendedDescriptionTranslatedTextInstanceOid = extendedDescriptionTranslatedTextInstanceOid;
    return this;
  }

   /**
   * Get extendedDescriptionTranslatedTextInstanceOid
   * @return extendedDescriptionTranslatedTextInstanceOid
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getExtendedDescriptionTranslatedTextInstanceOid() {
    return extendedDescriptionTranslatedTextInstanceOid;
  }

  public void setExtendedDescriptionTranslatedTextInstanceOid(Integer extendedDescriptionTranslatedTextInstanceOid) {
    this.extendedDescriptionTranslatedTextInstanceOid = extendedDescriptionTranslatedTextInstanceOid;
  }

  public ItemContent multimedia(List<ItemContentMultimedia> multimedia) {
    this.multimedia = multimedia;
    return this;
  }

  public ItemContent addMultimediaItem(ItemContentMultimedia multimediaItem) {
    this.multimedia.add(multimediaItem);
    return this;
  }

   /**
   * Get multimedia
   * @return multimedia
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ItemContentMultimedia> getMultimedia() {
    return multimedia;
  }

  public void setMultimedia(List<ItemContentMultimedia> multimedia) {
    this.multimedia = multimedia;
  }

  public ItemContent newItem(Boolean newItem) {
    this.newItem = newItem;
    return this;
  }

   /**
   * Get newItem
   * @return newItem
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getNewItem() {
    return newItem;
  }

  public void setNewItem(Boolean newItem) {
    this.newItem = newItem;
  }

  public ItemContent newItemEnd(String newItemEnd) {
    this.newItemEnd = newItemEnd;
    return this;
  }

   /**
   * Get newItemEnd
   * @return newItemEnd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNewItemEnd() {
    return newItemEnd;
  }

  public void setNewItemEnd(String newItemEnd) {
    this.newItemEnd = newItemEnd;
  }

  public ItemContent newItemStart(String newItemStart) {
    this.newItemStart = newItemStart;
    return this;
  }

   /**
   * Get newItemStart
   * @return newItemStart
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNewItemStart() {
    return newItemStart;
  }

  public void setNewItemStart(String newItemStart) {
    this.newItemStart = newItemStart;
  }

  public ItemContent viewUrl(String viewUrl) {
    this.viewUrl = viewUrl;
    return this;
  }

   /**
   * Get viewUrl
   * @return viewUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getViewUrl() {
    return viewUrl;
  }

  public void setViewUrl(String viewUrl) {
    this.viewUrl = viewUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemContent itemContent = (ItemContent) o;
    return Objects.equals(this.assignments, itemContent.assignments) &&
        Objects.equals(this.attributes, itemContent.attributes) &&
        Objects.equals(this.excludeFromSearch, itemContent.excludeFromSearch) &&
        Objects.equals(this.excludeFromTopSellers, itemContent.excludeFromTopSellers) &&
        Objects.equals(this.extendedDescription, itemContent.extendedDescription) &&
        Objects.equals(this.extendedDescriptionTranslatedTextInstanceOid, itemContent.extendedDescriptionTranslatedTextInstanceOid) &&
        Objects.equals(this.multimedia, itemContent.multimedia) &&
        Objects.equals(this.newItem, itemContent.newItem) &&
        Objects.equals(this.newItemEnd, itemContent.newItemEnd) &&
        Objects.equals(this.newItemStart, itemContent.newItemStart) &&
        Objects.equals(this.viewUrl, itemContent.viewUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignments, attributes, excludeFromSearch, excludeFromTopSellers, extendedDescription, extendedDescriptionTranslatedTextInstanceOid, multimedia, newItem, newItemEnd, newItemStart, viewUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemContent {\n");
    
    sb.append("    assignments: ").append(toIndentedString(assignments)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    excludeFromSearch: ").append(toIndentedString(excludeFromSearch)).append("\n");
    sb.append("    excludeFromTopSellers: ").append(toIndentedString(excludeFromTopSellers)).append("\n");
    sb.append("    extendedDescription: ").append(toIndentedString(extendedDescription)).append("\n");
    sb.append("    extendedDescriptionTranslatedTextInstanceOid: ").append(toIndentedString(extendedDescriptionTranslatedTextInstanceOid)).append("\n");
    sb.append("    multimedia: ").append(toIndentedString(multimedia)).append("\n");
    sb.append("    newItem: ").append(toIndentedString(newItem)).append("\n");
    sb.append("    newItemEnd: ").append(toIndentedString(newItemEnd)).append("\n");
    sb.append("    newItemStart: ").append(toIndentedString(newItemStart)).append("\n");
    sb.append("    viewUrl: ").append(toIndentedString(viewUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

