/**
 * UltraCart Rest API V2
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.ultracart.admin.v2.models.ItemAutoOrderStepArbitraryUnitCostSchedule;
import com.ultracart.admin.v2.models.ItemAutoOrderStepGrandfatherPricing;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ItemAutoOrderStep
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T13:26:11.909-04:00")
public class ItemAutoOrderStep   {
  @SerializedName("arbitrary_schedule_days")
  private Integer arbitraryScheduleDays = null;

  @SerializedName("arbitrary_unit_cost")
  private Double arbitraryUnitCost = null;

  @SerializedName("arbitrary_unit_cost_schedules")
  private List<ItemAutoOrderStepArbitraryUnitCostSchedule> arbitraryUnitCostSchedules = new ArrayList<ItemAutoOrderStepArbitraryUnitCostSchedule>();

  @SerializedName("grandfather_pricing")
  private List<ItemAutoOrderStepGrandfatherPricing> grandfatherPricing = new ArrayList<ItemAutoOrderStepGrandfatherPricing>();

  @SerializedName("managed_by")
  private String managedBy = null;

  @SerializedName("pause_days")
  private Integer pauseDays = null;

  @SerializedName("pause_unit_date")
  private String pauseUnitDate = null;

  @SerializedName("preshipment_notice_days")
  private Integer preshipmentNoticeDays = null;

  @SerializedName("recurring_merchant_item_id")
  private String recurringMerchantItemId = null;

  @SerializedName("recurring_merchant_item_oid")
  private Integer recurringMerchantItemOid = null;

  @SerializedName("repeat_count")
  private Integer repeatCount = null;

  @SerializedName("schedule")
  private String schedule = null;

  @SerializedName("subscribe_email_list_name")
  private String subscribeEmailListName = null;

  @SerializedName("subscribe_email_list_oid")
  private Integer subscribeEmailListOid = null;

  @SerializedName("type")
  private String type = null;

  public ItemAutoOrderStep arbitraryScheduleDays(Integer arbitraryScheduleDays) {
    this.arbitraryScheduleDays = arbitraryScheduleDays;
    return this;
  }

   /**
   * Get arbitraryScheduleDays
   * @return arbitraryScheduleDays
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getArbitraryScheduleDays() {
    return arbitraryScheduleDays;
  }

  public void setArbitraryScheduleDays(Integer arbitraryScheduleDays) {
    this.arbitraryScheduleDays = arbitraryScheduleDays;
  }

  public ItemAutoOrderStep arbitraryUnitCost(Double arbitraryUnitCost) {
    this.arbitraryUnitCost = arbitraryUnitCost;
    return this;
  }

   /**
   * Get arbitraryUnitCost
   * @return arbitraryUnitCost
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getArbitraryUnitCost() {
    return arbitraryUnitCost;
  }

  public void setArbitraryUnitCost(Double arbitraryUnitCost) {
    this.arbitraryUnitCost = arbitraryUnitCost;
  }

  public ItemAutoOrderStep arbitraryUnitCostSchedules(List<ItemAutoOrderStepArbitraryUnitCostSchedule> arbitraryUnitCostSchedules) {
    this.arbitraryUnitCostSchedules = arbitraryUnitCostSchedules;
    return this;
  }

  public ItemAutoOrderStep addArbitraryUnitCostSchedulesItem(ItemAutoOrderStepArbitraryUnitCostSchedule arbitraryUnitCostSchedulesItem) {
    this.arbitraryUnitCostSchedules.add(arbitraryUnitCostSchedulesItem);
    return this;
  }

   /**
   * Get arbitraryUnitCostSchedules
   * @return arbitraryUnitCostSchedules
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ItemAutoOrderStepArbitraryUnitCostSchedule> getArbitraryUnitCostSchedules() {
    return arbitraryUnitCostSchedules;
  }

  public void setArbitraryUnitCostSchedules(List<ItemAutoOrderStepArbitraryUnitCostSchedule> arbitraryUnitCostSchedules) {
    this.arbitraryUnitCostSchedules = arbitraryUnitCostSchedules;
  }

  public ItemAutoOrderStep grandfatherPricing(List<ItemAutoOrderStepGrandfatherPricing> grandfatherPricing) {
    this.grandfatherPricing = grandfatherPricing;
    return this;
  }

  public ItemAutoOrderStep addGrandfatherPricingItem(ItemAutoOrderStepGrandfatherPricing grandfatherPricingItem) {
    this.grandfatherPricing.add(grandfatherPricingItem);
    return this;
  }

   /**
   * Get grandfatherPricing
   * @return grandfatherPricing
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ItemAutoOrderStepGrandfatherPricing> getGrandfatherPricing() {
    return grandfatherPricing;
  }

  public void setGrandfatherPricing(List<ItemAutoOrderStepGrandfatherPricing> grandfatherPricing) {
    this.grandfatherPricing = grandfatherPricing;
  }

  public ItemAutoOrderStep managedBy(String managedBy) {
    this.managedBy = managedBy;
    return this;
  }

   /**
   * Get managedBy
   * @return managedBy
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getManagedBy() {
    return managedBy;
  }

  public void setManagedBy(String managedBy) {
    this.managedBy = managedBy;
  }

  public ItemAutoOrderStep pauseDays(Integer pauseDays) {
    this.pauseDays = pauseDays;
    return this;
  }

   /**
   * Get pauseDays
   * @return pauseDays
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPauseDays() {
    return pauseDays;
  }

  public void setPauseDays(Integer pauseDays) {
    this.pauseDays = pauseDays;
  }

  public ItemAutoOrderStep pauseUnitDate(String pauseUnitDate) {
    this.pauseUnitDate = pauseUnitDate;
    return this;
  }

   /**
   * Get pauseUnitDate
   * @return pauseUnitDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPauseUnitDate() {
    return pauseUnitDate;
  }

  public void setPauseUnitDate(String pauseUnitDate) {
    this.pauseUnitDate = pauseUnitDate;
  }

  public ItemAutoOrderStep preshipmentNoticeDays(Integer preshipmentNoticeDays) {
    this.preshipmentNoticeDays = preshipmentNoticeDays;
    return this;
  }

   /**
   * Get preshipmentNoticeDays
   * @return preshipmentNoticeDays
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPreshipmentNoticeDays() {
    return preshipmentNoticeDays;
  }

  public void setPreshipmentNoticeDays(Integer preshipmentNoticeDays) {
    this.preshipmentNoticeDays = preshipmentNoticeDays;
  }

  public ItemAutoOrderStep recurringMerchantItemId(String recurringMerchantItemId) {
    this.recurringMerchantItemId = recurringMerchantItemId;
    return this;
  }

   /**
   * Get recurringMerchantItemId
   * @return recurringMerchantItemId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRecurringMerchantItemId() {
    return recurringMerchantItemId;
  }

  public void setRecurringMerchantItemId(String recurringMerchantItemId) {
    this.recurringMerchantItemId = recurringMerchantItemId;
  }

  public ItemAutoOrderStep recurringMerchantItemOid(Integer recurringMerchantItemOid) {
    this.recurringMerchantItemOid = recurringMerchantItemOid;
    return this;
  }

   /**
   * Get recurringMerchantItemOid
   * @return recurringMerchantItemOid
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRecurringMerchantItemOid() {
    return recurringMerchantItemOid;
  }

  public void setRecurringMerchantItemOid(Integer recurringMerchantItemOid) {
    this.recurringMerchantItemOid = recurringMerchantItemOid;
  }

  public ItemAutoOrderStep repeatCount(Integer repeatCount) {
    this.repeatCount = repeatCount;
    return this;
  }

   /**
   * Get repeatCount
   * @return repeatCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRepeatCount() {
    return repeatCount;
  }

  public void setRepeatCount(Integer repeatCount) {
    this.repeatCount = repeatCount;
  }

  public ItemAutoOrderStep schedule(String schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSchedule() {
    return schedule;
  }

  public void setSchedule(String schedule) {
    this.schedule = schedule;
  }

  public ItemAutoOrderStep subscribeEmailListName(String subscribeEmailListName) {
    this.subscribeEmailListName = subscribeEmailListName;
    return this;
  }

   /**
   * Get subscribeEmailListName
   * @return subscribeEmailListName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubscribeEmailListName() {
    return subscribeEmailListName;
  }

  public void setSubscribeEmailListName(String subscribeEmailListName) {
    this.subscribeEmailListName = subscribeEmailListName;
  }

  public ItemAutoOrderStep subscribeEmailListOid(Integer subscribeEmailListOid) {
    this.subscribeEmailListOid = subscribeEmailListOid;
    return this;
  }

   /**
   * Get subscribeEmailListOid
   * @return subscribeEmailListOid
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSubscribeEmailListOid() {
    return subscribeEmailListOid;
  }

  public void setSubscribeEmailListOid(Integer subscribeEmailListOid) {
    this.subscribeEmailListOid = subscribeEmailListOid;
  }

  public ItemAutoOrderStep type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemAutoOrderStep itemAutoOrderStep = (ItemAutoOrderStep) o;
    return Objects.equals(this.arbitraryScheduleDays, itemAutoOrderStep.arbitraryScheduleDays) &&
        Objects.equals(this.arbitraryUnitCost, itemAutoOrderStep.arbitraryUnitCost) &&
        Objects.equals(this.arbitraryUnitCostSchedules, itemAutoOrderStep.arbitraryUnitCostSchedules) &&
        Objects.equals(this.grandfatherPricing, itemAutoOrderStep.grandfatherPricing) &&
        Objects.equals(this.managedBy, itemAutoOrderStep.managedBy) &&
        Objects.equals(this.pauseDays, itemAutoOrderStep.pauseDays) &&
        Objects.equals(this.pauseUnitDate, itemAutoOrderStep.pauseUnitDate) &&
        Objects.equals(this.preshipmentNoticeDays, itemAutoOrderStep.preshipmentNoticeDays) &&
        Objects.equals(this.recurringMerchantItemId, itemAutoOrderStep.recurringMerchantItemId) &&
        Objects.equals(this.recurringMerchantItemOid, itemAutoOrderStep.recurringMerchantItemOid) &&
        Objects.equals(this.repeatCount, itemAutoOrderStep.repeatCount) &&
        Objects.equals(this.schedule, itemAutoOrderStep.schedule) &&
        Objects.equals(this.subscribeEmailListName, itemAutoOrderStep.subscribeEmailListName) &&
        Objects.equals(this.subscribeEmailListOid, itemAutoOrderStep.subscribeEmailListOid) &&
        Objects.equals(this.type, itemAutoOrderStep.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arbitraryScheduleDays, arbitraryUnitCost, arbitraryUnitCostSchedules, grandfatherPricing, managedBy, pauseDays, pauseUnitDate, preshipmentNoticeDays, recurringMerchantItemId, recurringMerchantItemOid, repeatCount, schedule, subscribeEmailListName, subscribeEmailListOid, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemAutoOrderStep {\n");
    
    sb.append("    arbitraryScheduleDays: ").append(toIndentedString(arbitraryScheduleDays)).append("\n");
    sb.append("    arbitraryUnitCost: ").append(toIndentedString(arbitraryUnitCost)).append("\n");
    sb.append("    arbitraryUnitCostSchedules: ").append(toIndentedString(arbitraryUnitCostSchedules)).append("\n");
    sb.append("    grandfatherPricing: ").append(toIndentedString(grandfatherPricing)).append("\n");
    sb.append("    managedBy: ").append(toIndentedString(managedBy)).append("\n");
    sb.append("    pauseDays: ").append(toIndentedString(pauseDays)).append("\n");
    sb.append("    pauseUnitDate: ").append(toIndentedString(pauseUnitDate)).append("\n");
    sb.append("    preshipmentNoticeDays: ").append(toIndentedString(preshipmentNoticeDays)).append("\n");
    sb.append("    recurringMerchantItemId: ").append(toIndentedString(recurringMerchantItemId)).append("\n");
    sb.append("    recurringMerchantItemOid: ").append(toIndentedString(recurringMerchantItemOid)).append("\n");
    sb.append("    repeatCount: ").append(toIndentedString(repeatCount)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    subscribeEmailListName: ").append(toIndentedString(subscribeEmailListName)).append("\n");
    sb.append("    subscribeEmailListOid: ").append(toIndentedString(subscribeEmailListOid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

