/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ItemShippingCase
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-01-31T15:48:16.171-05:00")



public class ItemShippingCase {
  @SerializedName("case_label")
  private String caseLabel = null;

  @SerializedName("case_merchant_item_id")
  private String caseMerchantItemId = null;

  @SerializedName("case_merchant_item_oid")
  private Integer caseMerchantItemOid = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  public ItemShippingCase caseLabel(String caseLabel) {
    this.caseLabel = caseLabel;
    return this;
  }

   /**
   * Case label
   * @return caseLabel
  **/
  @ApiModelProperty(value = "Case label")
  public String getCaseLabel() {
    return caseLabel;
  }

  public void setCaseLabel(String caseLabel) {
    this.caseLabel = caseLabel;
  }

  public ItemShippingCase caseMerchantItemId(String caseMerchantItemId) {
    this.caseMerchantItemId = caseMerchantItemId;
    return this;
  }

   /**
   * Case item id
   * @return caseMerchantItemId
  **/
  @ApiModelProperty(value = "Case item id")
  public String getCaseMerchantItemId() {
    return caseMerchantItemId;
  }

  public void setCaseMerchantItemId(String caseMerchantItemId) {
    this.caseMerchantItemId = caseMerchantItemId;
  }

  public ItemShippingCase caseMerchantItemOid(Integer caseMerchantItemOid) {
    this.caseMerchantItemOid = caseMerchantItemOid;
    return this;
  }

   /**
   * Case item object identifier
   * @return caseMerchantItemOid
  **/
  @ApiModelProperty(value = "Case item object identifier")
  public Integer getCaseMerchantItemOid() {
    return caseMerchantItemOid;
  }

  public void setCaseMerchantItemOid(Integer caseMerchantItemOid) {
    this.caseMerchantItemOid = caseMerchantItemOid;
  }

  public ItemShippingCase quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Case quantity
   * @return quantity
  **/
  @ApiModelProperty(value = "Case quantity")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemShippingCase itemShippingCase = (ItemShippingCase) o;
    return Objects.equals(this.caseLabel, itemShippingCase.caseLabel) &&
        Objects.equals(this.caseMerchantItemId, itemShippingCase.caseMerchantItemId) &&
        Objects.equals(this.caseMerchantItemOid, itemShippingCase.caseMerchantItemOid) &&
        Objects.equals(this.quantity, itemShippingCase.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caseLabel, caseMerchantItemId, caseMerchantItemOid, quantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemShippingCase {\n");
    
    sb.append("    caseLabel: ").append(toIndentedString(caseLabel)).append("\n");
    sb.append("    caseMerchantItemId: ").append(toIndentedString(caseMerchantItemId)).append("\n");
    sb.append("    caseMerchantItemOid: ").append(toIndentedString(caseMerchantItemOid)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

