/**
 * UltraCart Rest API V2
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ItemCCBill
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-31T10:46:57.712-04:00")
public class ItemCCBill   {
  @SerializedName("ccbill_allowed_currencies")
  private String ccbillAllowedCurrencies = null;

  @SerializedName("ccbill_allowed_types")
  private String ccbillAllowedTypes = null;

  @SerializedName("ccbill_currency_code")
  private String ccbillCurrencyCode = null;

  @SerializedName("ccbill_form_name")
  private String ccbillFormName = null;

  @SerializedName("ccbill_subaccount_id")
  private String ccbillSubaccountId = null;

  @SerializedName("ccbill_subscription_type_id")
  private String ccbillSubscriptionTypeId = null;

  public ItemCCBill ccbillAllowedCurrencies(String ccbillAllowedCurrencies) {
    this.ccbillAllowedCurrencies = ccbillAllowedCurrencies;
    return this;
  }

   /**
   * Get ccbillAllowedCurrencies
   * @return ccbillAllowedCurrencies
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCcbillAllowedCurrencies() {
    return ccbillAllowedCurrencies;
  }

  public void setCcbillAllowedCurrencies(String ccbillAllowedCurrencies) {
    this.ccbillAllowedCurrencies = ccbillAllowedCurrencies;
  }

  public ItemCCBill ccbillAllowedTypes(String ccbillAllowedTypes) {
    this.ccbillAllowedTypes = ccbillAllowedTypes;
    return this;
  }

   /**
   * Get ccbillAllowedTypes
   * @return ccbillAllowedTypes
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCcbillAllowedTypes() {
    return ccbillAllowedTypes;
  }

  public void setCcbillAllowedTypes(String ccbillAllowedTypes) {
    this.ccbillAllowedTypes = ccbillAllowedTypes;
  }

  public ItemCCBill ccbillCurrencyCode(String ccbillCurrencyCode) {
    this.ccbillCurrencyCode = ccbillCurrencyCode;
    return this;
  }

   /**
   * Get ccbillCurrencyCode
   * @return ccbillCurrencyCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCcbillCurrencyCode() {
    return ccbillCurrencyCode;
  }

  public void setCcbillCurrencyCode(String ccbillCurrencyCode) {
    this.ccbillCurrencyCode = ccbillCurrencyCode;
  }

  public ItemCCBill ccbillFormName(String ccbillFormName) {
    this.ccbillFormName = ccbillFormName;
    return this;
  }

   /**
   * Get ccbillFormName
   * @return ccbillFormName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCcbillFormName() {
    return ccbillFormName;
  }

  public void setCcbillFormName(String ccbillFormName) {
    this.ccbillFormName = ccbillFormName;
  }

  public ItemCCBill ccbillSubaccountId(String ccbillSubaccountId) {
    this.ccbillSubaccountId = ccbillSubaccountId;
    return this;
  }

   /**
   * Get ccbillSubaccountId
   * @return ccbillSubaccountId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCcbillSubaccountId() {
    return ccbillSubaccountId;
  }

  public void setCcbillSubaccountId(String ccbillSubaccountId) {
    this.ccbillSubaccountId = ccbillSubaccountId;
  }

  public ItemCCBill ccbillSubscriptionTypeId(String ccbillSubscriptionTypeId) {
    this.ccbillSubscriptionTypeId = ccbillSubscriptionTypeId;
    return this;
  }

   /**
   * Get ccbillSubscriptionTypeId
   * @return ccbillSubscriptionTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCcbillSubscriptionTypeId() {
    return ccbillSubscriptionTypeId;
  }

  public void setCcbillSubscriptionTypeId(String ccbillSubscriptionTypeId) {
    this.ccbillSubscriptionTypeId = ccbillSubscriptionTypeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemCCBill itemCCBill = (ItemCCBill) o;
    return Objects.equals(this.ccbillAllowedCurrencies, itemCCBill.ccbillAllowedCurrencies) &&
        Objects.equals(this.ccbillAllowedTypes, itemCCBill.ccbillAllowedTypes) &&
        Objects.equals(this.ccbillCurrencyCode, itemCCBill.ccbillCurrencyCode) &&
        Objects.equals(this.ccbillFormName, itemCCBill.ccbillFormName) &&
        Objects.equals(this.ccbillSubaccountId, itemCCBill.ccbillSubaccountId) &&
        Objects.equals(this.ccbillSubscriptionTypeId, itemCCBill.ccbillSubscriptionTypeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ccbillAllowedCurrencies, ccbillAllowedTypes, ccbillCurrencyCode, ccbillFormName, ccbillSubaccountId, ccbillSubscriptionTypeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemCCBill {\n");
    
    sb.append("    ccbillAllowedCurrencies: ").append(toIndentedString(ccbillAllowedCurrencies)).append("\n");
    sb.append("    ccbillAllowedTypes: ").append(toIndentedString(ccbillAllowedTypes)).append("\n");
    sb.append("    ccbillCurrencyCode: ").append(toIndentedString(ccbillCurrencyCode)).append("\n");
    sb.append("    ccbillFormName: ").append(toIndentedString(ccbillFormName)).append("\n");
    sb.append("    ccbillSubaccountId: ").append(toIndentedString(ccbillSubaccountId)).append("\n");
    sb.append("    ccbillSubscriptionTypeId: ").append(toIndentedString(ccbillSubscriptionTypeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

