/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * ItemChannelPartnerMapping
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-05T15:48:24.518-04:00[America/Indianapolis]")
public class ItemChannelPartnerMapping {
  public static final String SERIALIZED_NAME_BARCODE_UA = "barcode_ua";
  @SerializedName(SERIALIZED_NAME_BARCODE_UA)
  private String barcodeUa;

  public static final String SERIALIZED_NAME_BARCODE_UC = "barcode_uc";
  @SerializedName(SERIALIZED_NAME_BARCODE_UC)
  private String barcodeUc;

  public static final String SERIALIZED_NAME_BARCODE_UI = "barcode_ui";
  @SerializedName(SERIALIZED_NAME_BARCODE_UI)
  private String barcodeUi;

  public static final String SERIALIZED_NAME_BARCODE_UK = "barcode_uk";
  @SerializedName(SERIALIZED_NAME_BARCODE_UK)
  private String barcodeUk;

  public static final String SERIALIZED_NAME_BUYER_CATALOG_NUMBER = "buyer_catalog_number";
  @SerializedName(SERIALIZED_NAME_BUYER_CATALOG_NUMBER)
  private String buyerCatalogNumber;

  public static final String SERIALIZED_NAME_BUYER_DPCI = "buyer_dpci";
  @SerializedName(SERIALIZED_NAME_BUYER_DPCI)
  private String buyerDpci;

  public static final String SERIALIZED_NAME_BUYER_ITEM_NUMBER = "buyer_item_number";
  @SerializedName(SERIALIZED_NAME_BUYER_ITEM_NUMBER)
  private String buyerItemNumber;

  public static final String SERIALIZED_NAME_CHANNEL_PARTNER_CODE = "channel_partner_code";
  @SerializedName(SERIALIZED_NAME_CHANNEL_PARTNER_CODE)
  private String channelPartnerCode;

  public static final String SERIALIZED_NAME_CHANNEL_PARTNER_OID = "channel_partner_oid";
  @SerializedName(SERIALIZED_NAME_CHANNEL_PARTNER_OID)
  private Integer channelPartnerOid;

  public static final String SERIALIZED_NAME_COST = "cost";
  @SerializedName(SERIALIZED_NAME_COST)
  private BigDecimal cost;

  public static final String SERIALIZED_NAME_FROM_ITEM_ID = "from_item_id";
  @SerializedName(SERIALIZED_NAME_FROM_ITEM_ID)
  private String fromItemId;

  public static final String SERIALIZED_NAME_FROM_SKU = "from_sku";
  @SerializedName(SERIALIZED_NAME_FROM_SKU)
  private String fromSku;

  public static final String SERIALIZED_NAME_MUTUALLY_DEFINED_NUMBER = "mutually_defined_number";
  @SerializedName(SERIALIZED_NAME_MUTUALLY_DEFINED_NUMBER)
  private String mutuallyDefinedNumber;

  public static final String SERIALIZED_NAME_QUANTITY_RATIO_CP = "quantity_ratio_cp";
  @SerializedName(SERIALIZED_NAME_QUANTITY_RATIO_CP)
  private Integer quantityRatioCp;

  public static final String SERIALIZED_NAME_QUANTITY_RATIO_UC = "quantity_ratio_uc";
  @SerializedName(SERIALIZED_NAME_QUANTITY_RATIO_UC)
  private Integer quantityRatioUc;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private String sku;

  public static final String SERIALIZED_NAME_UNIT_OF_MEASURE = "unit_of_measure";
  @SerializedName(SERIALIZED_NAME_UNIT_OF_MEASURE)
  private String unitOfMeasure;

  public static final String SERIALIZED_NAME_VENDOR_NUMBER = "vendor_number";
  @SerializedName(SERIALIZED_NAME_VENDOR_NUMBER)
  private String vendorNumber;

  public static final String SERIALIZED_NAME_VENDOR_STYLE_NUMBER = "vendor_style_number";
  @SerializedName(SERIALIZED_NAME_VENDOR_STYLE_NUMBER)
  private String vendorStyleNumber;

  public ItemChannelPartnerMapping() { 
  }

  public ItemChannelPartnerMapping barcodeUa(String barcodeUa) {
    
    this.barcodeUa = barcodeUa;
    return this;
  }

   /**
   * Barcode UA (EDI only)
   * @return barcodeUa
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Barcode UA (EDI only)")

  public String getBarcodeUa() {
    return barcodeUa;
  }


  public void setBarcodeUa(String barcodeUa) {
    this.barcodeUa = barcodeUa;
  }


  public ItemChannelPartnerMapping barcodeUc(String barcodeUc) {
    
    this.barcodeUc = barcodeUc;
    return this;
  }

   /**
   * Barcode UC (EDI only)
   * @return barcodeUc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Barcode UC (EDI only)")

  public String getBarcodeUc() {
    return barcodeUc;
  }


  public void setBarcodeUc(String barcodeUc) {
    this.barcodeUc = barcodeUc;
  }


  public ItemChannelPartnerMapping barcodeUi(String barcodeUi) {
    
    this.barcodeUi = barcodeUi;
    return this;
  }

   /**
   * Barcode UI (EDI only)
   * @return barcodeUi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Barcode UI (EDI only)")

  public String getBarcodeUi() {
    return barcodeUi;
  }


  public void setBarcodeUi(String barcodeUi) {
    this.barcodeUi = barcodeUi;
  }


  public ItemChannelPartnerMapping barcodeUk(String barcodeUk) {
    
    this.barcodeUk = barcodeUk;
    return this;
  }

   /**
   * Barcode UK (EDI only)
   * @return barcodeUk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Barcode UK (EDI only)")

  public String getBarcodeUk() {
    return barcodeUk;
  }


  public void setBarcodeUk(String barcodeUk) {
    this.barcodeUk = barcodeUk;
  }


  public ItemChannelPartnerMapping buyerCatalogNumber(String buyerCatalogNumber) {
    
    this.buyerCatalogNumber = buyerCatalogNumber;
    return this;
  }

   /**
   * Buyer catalog number (EDI only)
   * @return buyerCatalogNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Buyer catalog number (EDI only)")

  public String getBuyerCatalogNumber() {
    return buyerCatalogNumber;
  }


  public void setBuyerCatalogNumber(String buyerCatalogNumber) {
    this.buyerCatalogNumber = buyerCatalogNumber;
  }


  public ItemChannelPartnerMapping buyerDpci(String buyerDpci) {
    
    this.buyerDpci = buyerDpci;
    return this;
  }

   /**
   * Buyer DPCI (EDI only)
   * @return buyerDpci
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Buyer DPCI (EDI only)")

  public String getBuyerDpci() {
    return buyerDpci;
  }


  public void setBuyerDpci(String buyerDpci) {
    this.buyerDpci = buyerDpci;
  }


  public ItemChannelPartnerMapping buyerItemNumber(String buyerItemNumber) {
    
    this.buyerItemNumber = buyerItemNumber;
    return this;
  }

   /**
   * Buyer item number (EDI only)
   * @return buyerItemNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Buyer item number (EDI only)")

  public String getBuyerItemNumber() {
    return buyerItemNumber;
  }


  public void setBuyerItemNumber(String buyerItemNumber) {
    this.buyerItemNumber = buyerItemNumber;
  }


  public ItemChannelPartnerMapping channelPartnerCode(String channelPartnerCode) {
    
    this.channelPartnerCode = channelPartnerCode;
    return this;
  }

   /**
   * Channel partner code
   * @return channelPartnerCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Channel partner code")

  public String getChannelPartnerCode() {
    return channelPartnerCode;
  }


  public void setChannelPartnerCode(String channelPartnerCode) {
    this.channelPartnerCode = channelPartnerCode;
  }


  public ItemChannelPartnerMapping channelPartnerOid(Integer channelPartnerOid) {
    
    this.channelPartnerOid = channelPartnerOid;
    return this;
  }

   /**
   * Channel partner object identifier
   * @return channelPartnerOid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Channel partner object identifier")

  public Integer getChannelPartnerOid() {
    return channelPartnerOid;
  }


  public void setChannelPartnerOid(Integer channelPartnerOid) {
    this.channelPartnerOid = channelPartnerOid;
  }


  public ItemChannelPartnerMapping cost(BigDecimal cost) {
    
    this.cost = cost;
    return this;
  }

   /**
   * Cost given to this channel partner
   * @return cost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Cost given to this channel partner")

  public BigDecimal getCost() {
    return cost;
  }


  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }


  public ItemChannelPartnerMapping fromItemId(String fromItemId) {
    
    this.fromItemId = fromItemId;
    return this;
  }

   /**
   * From Item ID
   * @return fromItemId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "From Item ID")

  public String getFromItemId() {
    return fromItemId;
  }


  public void setFromItemId(String fromItemId) {
    this.fromItemId = fromItemId;
  }


  public ItemChannelPartnerMapping fromSku(String fromSku) {
    
    this.fromSku = fromSku;
    return this;
  }

   /**
   * From SKU
   * @return fromSku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "From SKU")

  public String getFromSku() {
    return fromSku;
  }


  public void setFromSku(String fromSku) {
    this.fromSku = fromSku;
  }


  public ItemChannelPartnerMapping mutuallyDefinedNumber(String mutuallyDefinedNumber) {
    
    this.mutuallyDefinedNumber = mutuallyDefinedNumber;
    return this;
  }

   /**
   * Mutually defined number (EDI only)
   * @return mutuallyDefinedNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Mutually defined number (EDI only)")

  public String getMutuallyDefinedNumber() {
    return mutuallyDefinedNumber;
  }


  public void setMutuallyDefinedNumber(String mutuallyDefinedNumber) {
    this.mutuallyDefinedNumber = mutuallyDefinedNumber;
  }


  public ItemChannelPartnerMapping quantityRatioCp(Integer quantityRatioCp) {
    
    this.quantityRatioCp = quantityRatioCp;
    return this;
  }

   /**
   * Ratio (Channel Partner)
   * @return quantityRatioCp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ratio (Channel Partner)")

  public Integer getQuantityRatioCp() {
    return quantityRatioCp;
  }


  public void setQuantityRatioCp(Integer quantityRatioCp) {
    this.quantityRatioCp = quantityRatioCp;
  }


  public ItemChannelPartnerMapping quantityRatioUc(Integer quantityRatioUc) {
    
    this.quantityRatioUc = quantityRatioUc;
    return this;
  }

   /**
   * Ratio (UltraCart)
   * @return quantityRatioUc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ratio (UltraCart)")

  public Integer getQuantityRatioUc() {
    return quantityRatioUc;
  }


  public void setQuantityRatioUc(Integer quantityRatioUc) {
    this.quantityRatioUc = quantityRatioUc;
  }


  public ItemChannelPartnerMapping sku(String sku) {
    
    this.sku = sku;
    return this;
  }

   /**
   * SKU
   * @return sku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SKU")

  public String getSku() {
    return sku;
  }


  public void setSku(String sku) {
    this.sku = sku;
  }


  public ItemChannelPartnerMapping unitOfMeasure(String unitOfMeasure) {
    
    this.unitOfMeasure = unitOfMeasure;
    return this;
  }

   /**
   * Unit of measure
   * @return unitOfMeasure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Unit of measure")

  public String getUnitOfMeasure() {
    return unitOfMeasure;
  }


  public void setUnitOfMeasure(String unitOfMeasure) {
    this.unitOfMeasure = unitOfMeasure;
  }


  public ItemChannelPartnerMapping vendorNumber(String vendorNumber) {
    
    this.vendorNumber = vendorNumber;
    return this;
  }

   /**
   * Vendor number (EDI only)
   * @return vendorNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Vendor number (EDI only)")

  public String getVendorNumber() {
    return vendorNumber;
  }


  public void setVendorNumber(String vendorNumber) {
    this.vendorNumber = vendorNumber;
  }


  public ItemChannelPartnerMapping vendorStyleNumber(String vendorStyleNumber) {
    
    this.vendorStyleNumber = vendorStyleNumber;
    return this;
  }

   /**
   * Vendor style number (EDI only)
   * @return vendorStyleNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Vendor style number (EDI only)")

  public String getVendorStyleNumber() {
    return vendorStyleNumber;
  }


  public void setVendorStyleNumber(String vendorStyleNumber) {
    this.vendorStyleNumber = vendorStyleNumber;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemChannelPartnerMapping itemChannelPartnerMapping = (ItemChannelPartnerMapping) o;
    return Objects.equals(this.barcodeUa, itemChannelPartnerMapping.barcodeUa) &&
        Objects.equals(this.barcodeUc, itemChannelPartnerMapping.barcodeUc) &&
        Objects.equals(this.barcodeUi, itemChannelPartnerMapping.barcodeUi) &&
        Objects.equals(this.barcodeUk, itemChannelPartnerMapping.barcodeUk) &&
        Objects.equals(this.buyerCatalogNumber, itemChannelPartnerMapping.buyerCatalogNumber) &&
        Objects.equals(this.buyerDpci, itemChannelPartnerMapping.buyerDpci) &&
        Objects.equals(this.buyerItemNumber, itemChannelPartnerMapping.buyerItemNumber) &&
        Objects.equals(this.channelPartnerCode, itemChannelPartnerMapping.channelPartnerCode) &&
        Objects.equals(this.channelPartnerOid, itemChannelPartnerMapping.channelPartnerOid) &&
        Objects.equals(this.cost, itemChannelPartnerMapping.cost) &&
        Objects.equals(this.fromItemId, itemChannelPartnerMapping.fromItemId) &&
        Objects.equals(this.fromSku, itemChannelPartnerMapping.fromSku) &&
        Objects.equals(this.mutuallyDefinedNumber, itemChannelPartnerMapping.mutuallyDefinedNumber) &&
        Objects.equals(this.quantityRatioCp, itemChannelPartnerMapping.quantityRatioCp) &&
        Objects.equals(this.quantityRatioUc, itemChannelPartnerMapping.quantityRatioUc) &&
        Objects.equals(this.sku, itemChannelPartnerMapping.sku) &&
        Objects.equals(this.unitOfMeasure, itemChannelPartnerMapping.unitOfMeasure) &&
        Objects.equals(this.vendorNumber, itemChannelPartnerMapping.vendorNumber) &&
        Objects.equals(this.vendorStyleNumber, itemChannelPartnerMapping.vendorStyleNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(barcodeUa, barcodeUc, barcodeUi, barcodeUk, buyerCatalogNumber, buyerDpci, buyerItemNumber, channelPartnerCode, channelPartnerOid, cost, fromItemId, fromSku, mutuallyDefinedNumber, quantityRatioCp, quantityRatioUc, sku, unitOfMeasure, vendorNumber, vendorStyleNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemChannelPartnerMapping {\n");
    sb.append("    barcodeUa: ").append(toIndentedString(barcodeUa)).append("\n");
    sb.append("    barcodeUc: ").append(toIndentedString(barcodeUc)).append("\n");
    sb.append("    barcodeUi: ").append(toIndentedString(barcodeUi)).append("\n");
    sb.append("    barcodeUk: ").append(toIndentedString(barcodeUk)).append("\n");
    sb.append("    buyerCatalogNumber: ").append(toIndentedString(buyerCatalogNumber)).append("\n");
    sb.append("    buyerDpci: ").append(toIndentedString(buyerDpci)).append("\n");
    sb.append("    buyerItemNumber: ").append(toIndentedString(buyerItemNumber)).append("\n");
    sb.append("    channelPartnerCode: ").append(toIndentedString(channelPartnerCode)).append("\n");
    sb.append("    channelPartnerOid: ").append(toIndentedString(channelPartnerOid)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    fromItemId: ").append(toIndentedString(fromItemId)).append("\n");
    sb.append("    fromSku: ").append(toIndentedString(fromSku)).append("\n");
    sb.append("    mutuallyDefinedNumber: ").append(toIndentedString(mutuallyDefinedNumber)).append("\n");
    sb.append("    quantityRatioCp: ").append(toIndentedString(quantityRatioCp)).append("\n");
    sb.append("    quantityRatioUc: ").append(toIndentedString(quantityRatioUc)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    unitOfMeasure: ").append(toIndentedString(unitOfMeasure)).append("\n");
    sb.append("    vendorNumber: ").append(toIndentedString(vendorNumber)).append("\n");
    sb.append("    vendorStyleNumber: ").append(toIndentedString(vendorStyleNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("barcode_ua");
    openapiFields.add("barcode_uc");
    openapiFields.add("barcode_ui");
    openapiFields.add("barcode_uk");
    openapiFields.add("buyer_catalog_number");
    openapiFields.add("buyer_dpci");
    openapiFields.add("buyer_item_number");
    openapiFields.add("channel_partner_code");
    openapiFields.add("channel_partner_oid");
    openapiFields.add("cost");
    openapiFields.add("from_item_id");
    openapiFields.add("from_sku");
    openapiFields.add("mutually_defined_number");
    openapiFields.add("quantity_ratio_cp");
    openapiFields.add("quantity_ratio_uc");
    openapiFields.add("sku");
    openapiFields.add("unit_of_measure");
    openapiFields.add("vendor_number");
    openapiFields.add("vendor_style_number");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ItemChannelPartnerMapping
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ItemChannelPartnerMapping.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ItemChannelPartnerMapping is not found in the empty JSON string", ItemChannelPartnerMapping.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ItemChannelPartnerMapping.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ItemChannelPartnerMapping` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("barcode_ua") != null && !jsonObj.get("barcode_ua").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `barcode_ua` to be a primitive type in the JSON string but got `%s`", jsonObj.get("barcode_ua").toString()));
      }
      if (jsonObj.get("barcode_uc") != null && !jsonObj.get("barcode_uc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `barcode_uc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("barcode_uc").toString()));
      }
      if (jsonObj.get("barcode_ui") != null && !jsonObj.get("barcode_ui").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `barcode_ui` to be a primitive type in the JSON string but got `%s`", jsonObj.get("barcode_ui").toString()));
      }
      if (jsonObj.get("barcode_uk") != null && !jsonObj.get("barcode_uk").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `barcode_uk` to be a primitive type in the JSON string but got `%s`", jsonObj.get("barcode_uk").toString()));
      }
      if (jsonObj.get("buyer_catalog_number") != null && !jsonObj.get("buyer_catalog_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `buyer_catalog_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buyer_catalog_number").toString()));
      }
      if (jsonObj.get("buyer_dpci") != null && !jsonObj.get("buyer_dpci").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `buyer_dpci` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buyer_dpci").toString()));
      }
      if (jsonObj.get("buyer_item_number") != null && !jsonObj.get("buyer_item_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `buyer_item_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("buyer_item_number").toString()));
      }
      if (jsonObj.get("channel_partner_code") != null && !jsonObj.get("channel_partner_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `channel_partner_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("channel_partner_code").toString()));
      }
      if (jsonObj.get("from_item_id") != null && !jsonObj.get("from_item_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `from_item_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from_item_id").toString()));
      }
      if (jsonObj.get("from_sku") != null && !jsonObj.get("from_sku").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `from_sku` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from_sku").toString()));
      }
      if (jsonObj.get("mutually_defined_number") != null && !jsonObj.get("mutually_defined_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mutually_defined_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mutually_defined_number").toString()));
      }
      if (jsonObj.get("sku") != null && !jsonObj.get("sku").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sku` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sku").toString()));
      }
      if (jsonObj.get("unit_of_measure") != null && !jsonObj.get("unit_of_measure").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unit_of_measure` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unit_of_measure").toString()));
      }
      if (jsonObj.get("vendor_number") != null && !jsonObj.get("vendor_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vendor_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vendor_number").toString()));
      }
      if (jsonObj.get("vendor_style_number") != null && !jsonObj.get("vendor_style_number").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vendor_style_number` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vendor_style_number").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ItemChannelPartnerMapping.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ItemChannelPartnerMapping' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ItemChannelPartnerMapping> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ItemChannelPartnerMapping.class));

       return (TypeAdapter<T>) new TypeAdapter<ItemChannelPartnerMapping>() {
           @Override
           public void write(JsonWriter out, ItemChannelPartnerMapping value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ItemChannelPartnerMapping read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ItemChannelPartnerMapping given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ItemChannelPartnerMapping
  * @throws IOException if the JSON string is invalid with respect to ItemChannelPartnerMapping
  */
  public static ItemChannelPartnerMapping fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ItemChannelPartnerMapping.class);
  }

 /**
  * Convert an instance of ItemChannelPartnerMapping to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

