/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * OauthDeviceAuthorizationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-13T13:29:31.532-04:00[America/Indianapolis]")
public class OauthDeviceAuthorizationResponse {
  public static final String SERIALIZED_NAME_DEVICE_CODE = "device_code";
  @SerializedName(SERIALIZED_NAME_DEVICE_CODE)
  private String deviceCode;

  public static final String SERIALIZED_NAME_EXPIRES_IN = "expires_in";
  @SerializedName(SERIALIZED_NAME_EXPIRES_IN)
  private Integer expiresIn;

  public static final String SERIALIZED_NAME_INTERVAL = "interval";
  @SerializedName(SERIALIZED_NAME_INTERVAL)
  private Integer interval;

  public static final String SERIALIZED_NAME_USER_CODE = "user_code";
  @SerializedName(SERIALIZED_NAME_USER_CODE)
  private String userCode;

  public static final String SERIALIZED_NAME_VERIFICATION_URI = "verification_uri";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_URI)
  private String verificationUri;

  public static final String SERIALIZED_NAME_VERIFICATION_URI_COMPLETE = "verification_uri_complete";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_URI_COMPLETE)
  private String verificationUriComplete;

  public OauthDeviceAuthorizationResponse() { 
  }

  public OauthDeviceAuthorizationResponse deviceCode(String deviceCode) {
    
    this.deviceCode = deviceCode;
    return this;
  }

   /**
   * The device verification code
   * @return deviceCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The device verification code")

  public String getDeviceCode() {
    return deviceCode;
  }


  public void setDeviceCode(String deviceCode) {
    this.deviceCode = deviceCode;
  }


  public OauthDeviceAuthorizationResponse expiresIn(Integer expiresIn) {
    
    this.expiresIn = expiresIn;
    return this;
  }

   /**
   * The lifetime in seconds of the device_code and user_code
   * @return expiresIn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The lifetime in seconds of the device_code and user_code")

  public Integer getExpiresIn() {
    return expiresIn;
  }


  public void setExpiresIn(Integer expiresIn) {
    this.expiresIn = expiresIn;
  }


  public OauthDeviceAuthorizationResponse interval(Integer interval) {
    
    this.interval = interval;
    return this;
  }

   /**
   * The minimum amount of time in seconds the client should wait between polling requests
   * @return interval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The minimum amount of time in seconds the client should wait between polling requests")

  public Integer getInterval() {
    return interval;
  }


  public void setInterval(Integer interval) {
    this.interval = interval;
  }


  public OauthDeviceAuthorizationResponse userCode(String userCode) {
    
    this.userCode = userCode;
    return this;
  }

   /**
   * The end-user verification code
   * @return userCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The end-user verification code")

  public String getUserCode() {
    return userCode;
  }


  public void setUserCode(String userCode) {
    this.userCode = userCode;
  }


  public OauthDeviceAuthorizationResponse verificationUri(String verificationUri) {
    
    this.verificationUri = verificationUri;
    return this;
  }

   /**
   * The end-user verification URI on the authorization server
   * @return verificationUri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The end-user verification URI on the authorization server")

  public String getVerificationUri() {
    return verificationUri;
  }


  public void setVerificationUri(String verificationUri) {
    this.verificationUri = verificationUri;
  }


  public OauthDeviceAuthorizationResponse verificationUriComplete(String verificationUriComplete) {
    
    this.verificationUriComplete = verificationUriComplete;
    return this;
  }

   /**
   * The verification URI with the user code pre-filled
   * @return verificationUriComplete
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The verification URI with the user code pre-filled")

  public String getVerificationUriComplete() {
    return verificationUriComplete;
  }


  public void setVerificationUriComplete(String verificationUriComplete) {
    this.verificationUriComplete = verificationUriComplete;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OauthDeviceAuthorizationResponse oauthDeviceAuthorizationResponse = (OauthDeviceAuthorizationResponse) o;
    return Objects.equals(this.deviceCode, oauthDeviceAuthorizationResponse.deviceCode) &&
        Objects.equals(this.expiresIn, oauthDeviceAuthorizationResponse.expiresIn) &&
        Objects.equals(this.interval, oauthDeviceAuthorizationResponse.interval) &&
        Objects.equals(this.userCode, oauthDeviceAuthorizationResponse.userCode) &&
        Objects.equals(this.verificationUri, oauthDeviceAuthorizationResponse.verificationUri) &&
        Objects.equals(this.verificationUriComplete, oauthDeviceAuthorizationResponse.verificationUriComplete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceCode, expiresIn, interval, userCode, verificationUri, verificationUriComplete);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OauthDeviceAuthorizationResponse {\n");
    sb.append("    deviceCode: ").append(toIndentedString(deviceCode)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    userCode: ").append(toIndentedString(userCode)).append("\n");
    sb.append("    verificationUri: ").append(toIndentedString(verificationUri)).append("\n");
    sb.append("    verificationUriComplete: ").append(toIndentedString(verificationUriComplete)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("device_code");
    openapiFields.add("expires_in");
    openapiFields.add("interval");
    openapiFields.add("user_code");
    openapiFields.add("verification_uri");
    openapiFields.add("verification_uri_complete");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OauthDeviceAuthorizationResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (OauthDeviceAuthorizationResponse.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in OauthDeviceAuthorizationResponse is not found in the empty JSON string", OauthDeviceAuthorizationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OauthDeviceAuthorizationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OauthDeviceAuthorizationResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("device_code") != null && !jsonObj.get("device_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `device_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("device_code").toString()));
      }
      if (jsonObj.get("user_code") != null && !jsonObj.get("user_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_code").toString()));
      }
      if (jsonObj.get("verification_uri") != null && !jsonObj.get("verification_uri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `verification_uri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verification_uri").toString()));
      }
      if (jsonObj.get("verification_uri_complete") != null && !jsonObj.get("verification_uri_complete").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `verification_uri_complete` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verification_uri_complete").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OauthDeviceAuthorizationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OauthDeviceAuthorizationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OauthDeviceAuthorizationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OauthDeviceAuthorizationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<OauthDeviceAuthorizationResponse>() {
           @Override
           public void write(JsonWriter out, OauthDeviceAuthorizationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OauthDeviceAuthorizationResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OauthDeviceAuthorizationResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OauthDeviceAuthorizationResponse
  * @throws IOException if the JSON string is invalid with respect to OauthDeviceAuthorizationResponse
  */
  public static OauthDeviceAuthorizationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OauthDeviceAuthorizationResponse.class);
  }

 /**
  * Convert an instance of OauthDeviceAuthorizationResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

