/**
 * UltraCart Rest API V2
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * OrderCoupon
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-03T17:26:54.699-04:00")
public class OrderCoupon   {
  @SerializedName("accounting_code")
  private String accountingCode = null;

  @SerializedName("base_coupon_code")
  private String baseCouponCode = null;

  @SerializedName("coupon_code")
  private String couponCode = null;

  public OrderCoupon accountingCode(String accountingCode) {
    this.accountingCode = accountingCode;
    return this;
  }

   /**
   * QuickBooks accounting code for this coupon
   * @return accountingCode
  **/
  @ApiModelProperty(example = "null", value = "QuickBooks accounting code for this coupon")
  public String getAccountingCode() {
    return accountingCode;
  }

  public void setAccountingCode(String accountingCode) {
    this.accountingCode = accountingCode;
  }

  public OrderCoupon baseCouponCode(String baseCouponCode) {
    this.baseCouponCode = baseCouponCode;
    return this;
  }

   /**
   * Coupon code configured by the merchant.  Will differ if the customer used a one time coupon code generated off this base coupon
   * @return baseCouponCode
  **/
  @ApiModelProperty(example = "null", value = "Coupon code configured by the merchant.  Will differ if the customer used a one time coupon code generated off this base coupon")
  public String getBaseCouponCode() {
    return baseCouponCode;
  }

  public void setBaseCouponCode(String baseCouponCode) {
    this.baseCouponCode = baseCouponCode;
  }

  public OrderCoupon couponCode(String couponCode) {
    this.couponCode = couponCode;
    return this;
  }

   /**
   * Coupon code entered by the customer
   * @return couponCode
  **/
  @ApiModelProperty(example = "null", value = "Coupon code entered by the customer")
  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderCoupon orderCoupon = (OrderCoupon) o;
    return Objects.equals(this.accountingCode, orderCoupon.accountingCode) &&
        Objects.equals(this.baseCouponCode, orderCoupon.baseCouponCode) &&
        Objects.equals(this.couponCode, orderCoupon.couponCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountingCode, baseCouponCode, couponCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderCoupon {\n");
    
    sb.append("    accountingCode: ").append(toIndentedString(accountingCode)).append("\n");
    sb.append("    baseCouponCode: ").append(toIndentedString(baseCouponCode)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

