/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * SfvbFileUploadRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-02T16:15:49.231-04:00[America/Indianapolis]")
public class SfvbFileUploadRequest {
  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private String comment;

  public static final String SERIALIZED_NAME_CREATE_IF_MISSING = "create_if_missing";
  @SerializedName(SERIALIZED_NAME_CREATE_IF_MISSING)
  private Boolean createIfMissing;

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public SfvbFileUploadRequest() { 
  }

  public SfvbFileUploadRequest comment(String comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * Optional comment recorded against the version this write creates.
   * @return comment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional comment recorded against the version this write creates.")

  public String getComment() {
    return comment;
  }


  public void setComment(String comment) {
    this.comment = comment;
  }


  public SfvbFileUploadRequest createIfMissing(Boolean createIfMissing) {
    
    this.createIfMissing = createIfMissing;
    return this;
  }

   /**
   * Create the file if it does not exist.  Defaults to true.
   * @return createIfMissing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Create the file if it does not exist.  Defaults to true.")

  public Boolean getCreateIfMissing() {
    return createIfMissing;
  }


  public void setCreateIfMissing(Boolean createIfMissing) {
    this.createIfMissing = createIfMissing;
  }


  public SfvbFileUploadRequest key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * The key returned when the upload URL was issued.
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The key returned when the upload URL was issued.")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public SfvbFileUploadRequest path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * Storefront path to write, for example /assets/imgs/hero.jpg.  The extension must match the one the upload URL was issued for, and must match the bytes.
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Storefront path to write, for example /assets/imgs/hero.jpg.  The extension must match the one the upload URL was issued for, and must match the bytes.")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SfvbFileUploadRequest sfvbFileUploadRequest = (SfvbFileUploadRequest) o;
    return Objects.equals(this.comment, sfvbFileUploadRequest.comment) &&
        Objects.equals(this.createIfMissing, sfvbFileUploadRequest.createIfMissing) &&
        Objects.equals(this.key, sfvbFileUploadRequest.key) &&
        Objects.equals(this.path, sfvbFileUploadRequest.path);
  }

  @Override
  public int hashCode() {
    return Objects.hash(comment, createIfMissing, key, path);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SfvbFileUploadRequest {\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    createIfMissing: ").append(toIndentedString(createIfMissing)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("comment");
    openapiFields.add("create_if_missing");
    openapiFields.add("key");
    openapiFields.add("path");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SfvbFileUploadRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (SfvbFileUploadRequest.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in SfvbFileUploadRequest is not found in the empty JSON string", SfvbFileUploadRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SfvbFileUploadRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SfvbFileUploadRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
      if (jsonObj.get("key") != null && !jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
      if (jsonObj.get("path") != null && !jsonObj.get("path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("path").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SfvbFileUploadRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SfvbFileUploadRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SfvbFileUploadRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SfvbFileUploadRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SfvbFileUploadRequest>() {
           @Override
           public void write(JsonWriter out, SfvbFileUploadRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SfvbFileUploadRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SfvbFileUploadRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SfvbFileUploadRequest
  * @throws IOException if the JSON string is invalid with respect to SfvbFileUploadRequest
  */
  public static SfvbFileUploadRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SfvbFileUploadRequest.class);
  }

 /**
  * Convert an instance of SfvbFileUploadRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

