/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ultracart.admin.v2.models.SfvbLibraryInstallRecord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * SfvbLibraryInstallsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SfvbLibraryInstallsResponse {
  public static final String SERIALIZED_NAME_INSTALLS = "installs";
  @SerializedName(SERIALIZED_NAME_INSTALLS)
  private List<SfvbLibraryInstallRecord> installs = null;

  public SfvbLibraryInstallsResponse() { 
  }

  public SfvbLibraryInstallsResponse installs(List<SfvbLibraryInstallRecord> installs) {
    
    this.installs = installs;
    return this;
  }

  public SfvbLibraryInstallsResponse addInstallsItem(SfvbLibraryInstallRecord installsItem) {
    if (this.installs == null) {
      this.installs = new ArrayList<>();
    }
    this.installs.add(installsItem);
    return this;
  }

   /**
   * The newest install of each entry on the storefront.
   * @return installs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The newest install of each entry on the storefront.")

  public List<SfvbLibraryInstallRecord> getInstalls() {
    return installs;
  }


  public void setInstalls(List<SfvbLibraryInstallRecord> installs) {
    this.installs = installs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SfvbLibraryInstallsResponse sfvbLibraryInstallsResponse = (SfvbLibraryInstallsResponse) o;
    return Objects.equals(this.installs, sfvbLibraryInstallsResponse.installs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(installs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SfvbLibraryInstallsResponse {\n");
    sb.append("    installs: ").append(toIndentedString(installs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("installs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SfvbLibraryInstallsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (SfvbLibraryInstallsResponse.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in SfvbLibraryInstallsResponse is not found in the empty JSON string", SfvbLibraryInstallsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SfvbLibraryInstallsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SfvbLibraryInstallsResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      JsonArray jsonArrayinstalls = jsonObj.getAsJsonArray("installs");
      if (jsonArrayinstalls != null) {
        // ensure the json data is an array
        if (!jsonObj.get("installs").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `installs` to be an array in the JSON string but got `%s`", jsonObj.get("installs").toString()));
        }

        // validate the optional field `installs` (array)
        for (int i = 0; i < jsonArrayinstalls.size(); i++) {
          SfvbLibraryInstallRecord.validateJsonObject(jsonArrayinstalls.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SfvbLibraryInstallsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SfvbLibraryInstallsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SfvbLibraryInstallsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SfvbLibraryInstallsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<SfvbLibraryInstallsResponse>() {
           @Override
           public void write(JsonWriter out, SfvbLibraryInstallsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SfvbLibraryInstallsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SfvbLibraryInstallsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SfvbLibraryInstallsResponse
  * @throws IOException if the JSON string is invalid with respect to SfvbLibraryInstallsResponse
  */
  public static SfvbLibraryInstallsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SfvbLibraryInstallsResponse.class);
  }

 /**
  * Convert an instance of SfvbLibraryInstallsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

