/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * SfvbTestOrder
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SfvbTestOrder {
  public static final String SERIALIZED_NAME_AUTO_ORDER = "auto_order";
  @SerializedName(SERIALIZED_NAME_AUTO_ORDER)
  private Boolean autoOrder;

  public static final String SERIALIZED_NAME_CREATED = "created";
  @SerializedName(SERIALIZED_NAME_CREATED)
  private String created;

  public static final String SERIALIZED_NAME_CURRENCY_CODE = "currency_code";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;

  public static final String SERIALIZED_NAME_DIGITAL_ITEMS = "digital_items";
  @SerializedName(SERIALIZED_NAME_DIGITAL_ITEMS)
  private Boolean digitalItems;

  public static final String SERIALIZED_NAME_ITEM_COUNT = "item_count";
  @SerializedName(SERIALIZED_NAME_ITEM_COUNT)
  private Integer itemCount;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  private String orderId;

  public static final String SERIALIZED_NAME_PAYMENT_METHOD = "payment_method";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHOD)
  private String paymentMethod;

  public static final String SERIALIZED_NAME_STAGE = "stage";
  @SerializedName(SERIALIZED_NAME_STAGE)
  private String stage;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private String total;

  public SfvbTestOrder() { 
  }

  public SfvbTestOrder autoOrder(Boolean autoOrder) {
    
    this.autoOrder = autoOrder;
    return this;
  }

   /**
   * True when the order started an auto order, for working on the subscription pages.
   * @return autoOrder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "True when the order started an auto order, for working on the subscription pages.")

  public Boolean getAutoOrder() {
    return autoOrder;
  }


  public void setAutoOrder(Boolean autoOrder) {
    this.autoOrder = autoOrder;
  }


  public SfvbTestOrder created(String created) {
    
    this.created = created;
    return this;
  }

   /**
   * When the order was placed, ISO-8601 in UTC.
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "When the order was placed, ISO-8601 in UTC.")

  public String getCreated() {
    return created;
  }


  public void setCreated(String created) {
    this.created = created;
  }


  public SfvbTestOrder currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * The currency of the total.
   * @return currencyCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The currency of the total.")

  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public SfvbTestOrder digitalItems(Boolean digitalItems) {
    
    this.digitalItems = digitalItems;
    return this;
  }

   /**
   * True when the order has digital downloads, for working on the digital download page.
   * @return digitalItems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "True when the order has digital downloads, for working on the digital download page.")

  public Boolean getDigitalItems() {
    return digitalItems;
  }


  public void setDigitalItems(Boolean digitalItems) {
    this.digitalItems = digitalItems;
  }


  public SfvbTestOrder itemCount(Integer itemCount) {
    
    this.itemCount = itemCount;
    return this;
  }

   /**
   * How many item lines the order has.
   * @return itemCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "How many item lines the order has.")

  public Integer getItemCount() {
    return itemCount;
  }


  public void setItemCount(Integer itemCount) {
    this.itemCount = itemCount;
  }


  public SfvbTestOrder orderId(String orderId) {
    
    this.orderId = orderId;
    return this;
  }

   /**
   * The order id.  Pass it as a render&#39;s context_order_id.
   * @return orderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The order id.  Pass it as a render's context_order_id.")

  public String getOrderId() {
    return orderId;
  }


  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }


  public SfvbTestOrder paymentMethod(String paymentMethod) {
    
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * How the order was paid, such as Credit Card or PayPal.
   * @return paymentMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "How the order was paid, such as Credit Card or PayPal.")

  public String getPaymentMethod() {
    return paymentMethod;
  }


  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public SfvbTestOrder stage(String stage) {
    
    this.stage = stage;
    return this;
  }

   /**
   * The order&#39;s current stage code, such as CO (completed), SD (shipping department) or AR (accounts receivable).
   * @return stage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The order's current stage code, such as CO (completed), SD (shipping department) or AR (accounts receivable).")

  public String getStage() {
    return stage;
  }


  public void setStage(String stage) {
    this.stage = stage;
  }


  public SfvbTestOrder total(String total) {
    
    this.total = total;
    return this;
  }

   /**
   * The order total as a decimal string.
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The order total as a decimal string.")

  public String getTotal() {
    return total;
  }


  public void setTotal(String total) {
    this.total = total;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SfvbTestOrder sfvbTestOrder = (SfvbTestOrder) o;
    return Objects.equals(this.autoOrder, sfvbTestOrder.autoOrder) &&
        Objects.equals(this.created, sfvbTestOrder.created) &&
        Objects.equals(this.currencyCode, sfvbTestOrder.currencyCode) &&
        Objects.equals(this.digitalItems, sfvbTestOrder.digitalItems) &&
        Objects.equals(this.itemCount, sfvbTestOrder.itemCount) &&
        Objects.equals(this.orderId, sfvbTestOrder.orderId) &&
        Objects.equals(this.paymentMethod, sfvbTestOrder.paymentMethod) &&
        Objects.equals(this.stage, sfvbTestOrder.stage) &&
        Objects.equals(this.total, sfvbTestOrder.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoOrder, created, currencyCode, digitalItems, itemCount, orderId, paymentMethod, stage, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SfvbTestOrder {\n");
    sb.append("    autoOrder: ").append(toIndentedString(autoOrder)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    digitalItems: ").append(toIndentedString(digitalItems)).append("\n");
    sb.append("    itemCount: ").append(toIndentedString(itemCount)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("auto_order");
    openapiFields.add("created");
    openapiFields.add("currency_code");
    openapiFields.add("digital_items");
    openapiFields.add("item_count");
    openapiFields.add("order_id");
    openapiFields.add("payment_method");
    openapiFields.add("stage");
    openapiFields.add("total");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SfvbTestOrder
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (SfvbTestOrder.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in SfvbTestOrder is not found in the empty JSON string", SfvbTestOrder.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SfvbTestOrder.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SfvbTestOrder` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("created") != null && !jsonObj.get("created").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created").toString()));
      }
      if (jsonObj.get("currency_code") != null && !jsonObj.get("currency_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency_code").toString()));
      }
      if (jsonObj.get("order_id") != null && !jsonObj.get("order_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `order_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("order_id").toString()));
      }
      if (jsonObj.get("payment_method") != null && !jsonObj.get("payment_method").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `payment_method` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payment_method").toString()));
      }
      if (jsonObj.get("stage") != null && !jsonObj.get("stage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stage").toString()));
      }
      if (jsonObj.get("total") != null && !jsonObj.get("total").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `total` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SfvbTestOrder.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SfvbTestOrder' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SfvbTestOrder> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SfvbTestOrder.class));

       return (TypeAdapter<T>) new TypeAdapter<SfvbTestOrder>() {
           @Override
           public void write(JsonWriter out, SfvbTestOrder value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SfvbTestOrder read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SfvbTestOrder given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SfvbTestOrder
  * @throws IOException if the JSON string is invalid with respect to SfvbTestOrder
  */
  public static SfvbTestOrder fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SfvbTestOrder.class);
  }

 /**
  * Convert an instance of SfvbTestOrder to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

