/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ultracart.admin.v2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.ultracart.admin.v2.util.JSON;

/**
 * SfvbNotFoundEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SfvbNotFoundEntry {
  public static final String SERIALIZED_NAME_BOT_HITS = "bot_hits";
  @SerializedName(SERIALIZED_NAME_BOT_HITS)
  private Integer botHits;

  public static final String SERIALIZED_NAME_BOT_SHARE = "bot_share";
  @SerializedName(SERIALIZED_NAME_BOT_SHARE)
  private Object botShare;

  public static final String SERIALIZED_NAME_COUNTED_HITS = "counted_hits";
  @SerializedName(SERIALIZED_NAME_COUNTED_HITS)
  private Integer countedHits;

  public static final String SERIALIZED_NAME_FIRST_SEEN_DTS = "first_seen_dts";
  @SerializedName(SERIALIZED_NAME_FIRST_SEEN_DTS)
  private String firstSeenDts;

  public static final String SERIALIZED_NAME_HITS = "hits";
  @SerializedName(SERIALIZED_NAME_HITS)
  private Integer hits;

  public static final String SERIALIZED_NAME_IGNORED = "ignored";
  @SerializedName(SERIALIZED_NAME_IGNORED)
  private Boolean ignored;

  public static final String SERIALIZED_NAME_LAST_SEEN_DTS = "last_seen_dts";
  @SerializedName(SERIALIZED_NAME_LAST_SEEN_DTS)
  private String lastSeenDts;

  public static final String SERIALIZED_NAME_NOT_FOUND_ID = "not_found_id";
  @SerializedName(SERIALIZED_NAME_NOT_FOUND_ID)
  private String notFoundId;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_REDIRECTED_TO = "redirected_to";
  @SerializedName(SERIALIZED_NAME_REDIRECTED_TO)
  private String redirectedTo;

  public static final String SERIALIZED_NAME_REFERRER_HOSTS = "referrer_hosts";
  @SerializedName(SERIALIZED_NAME_REFERRER_HOSTS)
  private List<String> referrerHosts = null;

  public SfvbNotFoundEntry() { 
  }

  public SfvbNotFoundEntry botHits(Integer botHits) {
    
    this.botHits = botHits;
    return this;
  }

   /**
   * Bot hits since bot counting began on this entry.  Empty when not yet counted.
   * @return botHits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Bot hits since bot counting began on this entry.  Empty when not yet counted.")

  public Integer getBotHits() {
    return botHits;
  }


  public void setBotHits(Integer botHits) {
    this.botHits = botHits;
  }


  public SfvbNotFoundEntry botShare(Object botShare) {
    
    this.botShare = botShare;
    return this;
  }

   /**
   * bot_hits divided by counted_hits, 0 to 1.  Empty when not yet counted.
   * @return botShare
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "bot_hits divided by counted_hits, 0 to 1.  Empty when not yet counted.")

  public Object getBotShare() {
    return botShare;
  }


  public void setBotShare(Object botShare) {
    this.botShare = botShare;
  }


  public SfvbNotFoundEntry countedHits(Integer countedHits) {
    
    this.countedHits = countedHits;
    return this;
  }

   /**
   * Hits since bot counting began, the base for bot_share.
   * @return countedHits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hits since bot counting began, the base for bot_share.")

  public Integer getCountedHits() {
    return countedHits;
  }


  public void setCountedHits(Integer countedHits) {
    this.countedHits = countedHits;
  }


  public SfvbNotFoundEntry firstSeenDts(String firstSeenDts) {
    
    this.firstSeenDts = firstSeenDts;
    return this;
  }

   /**
   * First hit, ISO 8601.
   * @return firstSeenDts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "First hit, ISO 8601.")

  public String getFirstSeenDts() {
    return firstSeenDts;
  }


  public void setFirstSeenDts(String firstSeenDts) {
    this.firstSeenDts = firstSeenDts;
  }


  public SfvbNotFoundEntry hits(Integer hits) {
    
    this.hits = hits;
    return this;
  }

   /**
   * Every recorded hit, bots included.
   * @return hits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Every recorded hit, bots included.")

  public Integer getHits() {
    return hits;
  }


  public void setHits(Integer hits) {
    this.hits = hits;
  }


  public SfvbNotFoundEntry ignored(Boolean ignored) {
    
    this.ignored = ignored;
    return this;
  }

   /**
   * True when the entry is ignored and no longer counts.
   * @return ignored
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "True when the entry is ignored and no longer counts.")

  public Boolean getIgnored() {
    return ignored;
  }


  public void setIgnored(Boolean ignored) {
    this.ignored = ignored;
  }


  public SfvbNotFoundEntry lastSeenDts(String lastSeenDts) {
    
    this.lastSeenDts = lastSeenDts;
    return this;
  }

   /**
   * Latest hit, ISO 8601.
   * @return lastSeenDts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Latest hit, ISO 8601.")

  public String getLastSeenDts() {
    return lastSeenDts;
  }


  public void setLastSeenDts(String lastSeenDts) {
    this.lastSeenDts = lastSeenDts;
  }


  public SfvbNotFoundEntry notFoundId(String notFoundId) {
    
    this.notFoundId = notFoundId;
    return this;
  }

   /**
   * The entry&#39;s id.
   * @return notFoundId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The entry's id.")

  public String getNotFoundId() {
    return notFoundId;
  }


  public void setNotFoundId(String notFoundId) {
    this.notFoundId = notFoundId;
  }


  public SfvbNotFoundEntry path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * The path, without its query string.  Token-like segments show as {token} unless asked for.
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The path, without its query string.  Token-like segments show as {token} unless asked for.")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public SfvbNotFoundEntry redirectedTo(String redirectedTo) {
    
    this.redirectedTo = redirectedTo;
    return this;
  }

   /**
   * Where a redirect rule now sends this path, when one does.
   * @return redirectedTo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Where a redirect rule now sends this path, when one does.")

  public String getRedirectedTo() {
    return redirectedTo;
  }


  public void setRedirectedTo(String redirectedTo) {
    this.redirectedTo = redirectedTo;
  }


  public SfvbNotFoundEntry referrerHosts(List<String> referrerHosts) {
    
    this.referrerHosts = referrerHosts;
    return this;
  }

  public SfvbNotFoundEntry addReferrerHostsItem(String referrerHostsItem) {
    if (this.referrerHosts == null) {
      this.referrerHosts = new ArrayList<>();
    }
    this.referrerHosts.add(referrerHostsItem);
    return this;
  }

   /**
   * Hosts of the pages that linked to it.
   * @return referrerHosts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hosts of the pages that linked to it.")

  public List<String> getReferrerHosts() {
    return referrerHosts;
  }


  public void setReferrerHosts(List<String> referrerHosts) {
    this.referrerHosts = referrerHosts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SfvbNotFoundEntry sfvbNotFoundEntry = (SfvbNotFoundEntry) o;
    return Objects.equals(this.botHits, sfvbNotFoundEntry.botHits) &&
        Objects.equals(this.botShare, sfvbNotFoundEntry.botShare) &&
        Objects.equals(this.countedHits, sfvbNotFoundEntry.countedHits) &&
        Objects.equals(this.firstSeenDts, sfvbNotFoundEntry.firstSeenDts) &&
        Objects.equals(this.hits, sfvbNotFoundEntry.hits) &&
        Objects.equals(this.ignored, sfvbNotFoundEntry.ignored) &&
        Objects.equals(this.lastSeenDts, sfvbNotFoundEntry.lastSeenDts) &&
        Objects.equals(this.notFoundId, sfvbNotFoundEntry.notFoundId) &&
        Objects.equals(this.path, sfvbNotFoundEntry.path) &&
        Objects.equals(this.redirectedTo, sfvbNotFoundEntry.redirectedTo) &&
        Objects.equals(this.referrerHosts, sfvbNotFoundEntry.referrerHosts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(botHits, botShare, countedHits, firstSeenDts, hits, ignored, lastSeenDts, notFoundId, path, redirectedTo, referrerHosts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SfvbNotFoundEntry {\n");
    sb.append("    botHits: ").append(toIndentedString(botHits)).append("\n");
    sb.append("    botShare: ").append(toIndentedString(botShare)).append("\n");
    sb.append("    countedHits: ").append(toIndentedString(countedHits)).append("\n");
    sb.append("    firstSeenDts: ").append(toIndentedString(firstSeenDts)).append("\n");
    sb.append("    hits: ").append(toIndentedString(hits)).append("\n");
    sb.append("    ignored: ").append(toIndentedString(ignored)).append("\n");
    sb.append("    lastSeenDts: ").append(toIndentedString(lastSeenDts)).append("\n");
    sb.append("    notFoundId: ").append(toIndentedString(notFoundId)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    redirectedTo: ").append(toIndentedString(redirectedTo)).append("\n");
    sb.append("    referrerHosts: ").append(toIndentedString(referrerHosts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bot_hits");
    openapiFields.add("bot_share");
    openapiFields.add("counted_hits");
    openapiFields.add("first_seen_dts");
    openapiFields.add("hits");
    openapiFields.add("ignored");
    openapiFields.add("last_seen_dts");
    openapiFields.add("not_found_id");
    openapiFields.add("path");
    openapiFields.add("redirected_to");
    openapiFields.add("referrer_hosts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SfvbNotFoundEntry
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (SfvbNotFoundEntry.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in SfvbNotFoundEntry is not found in the empty JSON string", SfvbNotFoundEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!SfvbNotFoundEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SfvbNotFoundEntry` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("first_seen_dts") != null && !jsonObj.get("first_seen_dts").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `first_seen_dts` to be a primitive type in the JSON string but got `%s`", jsonObj.get("first_seen_dts").toString()));
      }
      if (jsonObj.get("last_seen_dts") != null && !jsonObj.get("last_seen_dts").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `last_seen_dts` to be a primitive type in the JSON string but got `%s`", jsonObj.get("last_seen_dts").toString()));
      }
      if (jsonObj.get("not_found_id") != null && !jsonObj.get("not_found_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `not_found_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("not_found_id").toString()));
      }
      if (jsonObj.get("path") != null && !jsonObj.get("path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("path").toString()));
      }
      if (jsonObj.get("redirected_to") != null && !jsonObj.get("redirected_to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `redirected_to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("redirected_to").toString()));
      }
      // ensure the json data is an array
      if (jsonObj.get("referrer_hosts") != null && !jsonObj.get("referrer_hosts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `referrer_hosts` to be an array in the JSON string but got `%s`", jsonObj.get("referrer_hosts").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SfvbNotFoundEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SfvbNotFoundEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SfvbNotFoundEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SfvbNotFoundEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<SfvbNotFoundEntry>() {
           @Override
           public void write(JsonWriter out, SfvbNotFoundEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SfvbNotFoundEntry read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SfvbNotFoundEntry given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SfvbNotFoundEntry
  * @throws IOException if the JSON string is invalid with respect to SfvbNotFoundEntry
  */
  public static SfvbNotFoundEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SfvbNotFoundEntry.class);
  }

 /**
  * Convert an instance of SfvbNotFoundEntry to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

